const questions = [

  // ╔══════════════════════════════╗
  // ║         易  EASY  (72題)     ║
  // ╚══════════════════════════════╝

  // ── 字音 (20題) ───────────────
  { id:'e-p-01', type:'pronunciation', difficulty:1,
    question:'「音樂」的「樂」正確讀音是？',
    options:['ㄌㄜˋ','ㄩㄝˋ','ㄌㄜˊ','ㄩㄝˊ'], answer:1,
    explanation:'「音樂」念 ㄩㄝˋ；「快樂」的「樂」念 ㄌㄜˋ。' },
  { id:'e-p-02', type:'pronunciation', difficulty:1,
    question:'「行為」的「行」正確讀音是？',
    options:['ㄏㄤˊ','ㄒㄧㄥˊ','ㄏㄥˊ','ㄒㄧㄥˋ'], answer:1,
    explanation:'「行為」的「行」念 ㄒㄧㄥˊ；ㄏㄤˊ 用於「行列」「行業」。' },
  { id:'e-p-03', type:'pronunciation', difficulty:1,
    question:'「假設」的「假」正確讀音是？',
    options:['ㄐㄧㄚˋ','ㄐㄧㄚˇ','ㄐㄧㄚ','ㄑㄧㄚˇ'], answer:1,
    explanation:'「假設」念 ㄐㄧㄚˇ；「放假」的「假」才念 ㄐㄧㄚˋ。' },
  { id:'e-p-04', type:'pronunciation', difficulty:1,
    question:'「成長」的「長」正確讀音是？',
    options:['ㄔㄤˊ','ㄓㄤˇ','ㄓㄤˊ','ㄔㄤˇ'], answer:1,
    explanation:'「成長」念 ㄓㄤˇ；「長度」的「長」念 ㄔㄤˊ。' },
  { id:'e-p-05', type:'pronunciation', difficulty:1,
    question:'「重要」的「重」正確讀音是？',
    options:['ㄔㄨㄥˊ','ㄓㄨㄥˋ','ㄔㄨㄥˋ','ㄓㄨㄥˊ'], answer:1,
    explanation:'「重要」念 ㄓㄨㄥˋ（分量重）；「重複」的「重」念 ㄔㄨㄥˊ（再次）。' },
  { id:'e-p-06', type:'pronunciation', difficulty:1,
    question:'「給予」的「給」正確讀音是？',
    options:['ㄍㄟˇ','ㄍㄟˋ','ㄐㄧˇ','ㄐㄧˋ'], answer:2,
    explanation:'「給予」念 ㄐㄧˇ，為正式書面語；「給你」的「給」念 ㄍㄟˇ 是口語。' },
  { id:'e-p-07', type:'pronunciation', difficulty:1,
    question:'「說服」的「服」正確讀音是？',
    options:['ㄈㄨˋ','ㄈㄨˊ','ㄅㄨˊ','ㄅㄨˋ'], answer:1,
    explanation:'「說服」念 ㄕㄨㄛ ㄈㄨˊ，第二聲；念 ㄈㄨˋ 是常見錯誤。' },
  { id:'e-p-08', type:'pronunciation', difficulty:1,
    question:'「任何」的「任」正確讀音是？',
    options:['ㄖㄣˊ','ㄖㄣˋ','ㄖㄢˊ','ㄖㄢˋ'], answer:1,
    explanation:'「任何」的「任」念 ㄖㄣˋ（任意、任憑）；ㄖㄣˊ 是「人」。' },
  { id:'e-p-09', type:'pronunciation', difficulty:1,
    question:'「空白」的「空」正確讀音是？',
    options:['ㄎㄨㄥ','ㄎㄨㄥˋ','ㄎㄨㄥˊ','ㄎㄨㄥˇ'], answer:1,
    explanation:'「空白」念 ㄎㄨㄥˋ（空缺、空閒）；「天空」的「空」念 ㄎㄨㄥ（第一聲）。' },
  { id:'e-p-10', type:'pronunciation', difficulty:1,
    question:'「好奇」的「好」正確讀音是？',
    options:['ㄏㄠˇ','ㄏㄠˋ','ㄏㄠ','ㄏㄠˊ'], answer:1,
    explanation:'「好奇」念 ㄏㄠˋ，「好」作動詞（喜好）念 ㄏㄠˋ；「好人」的「好」念 ㄏㄠˇ。' },
  { id:'e-p-11', type:'pronunciation', difficulty:1,
    question:'「強迫」的「強」正確讀音是？',
    options:['ㄑㄧㄤˊ','ㄑㄧㄤˇ','ㄐㄧㄤˋ','ㄑㄧㄤ'], answer:1,
    explanation:'「強迫」念 ㄑㄧㄤˇ（勉強、強迫）；「強大」的「強」念 ㄑㄧㄤˊ（第二聲）。' },
  { id:'e-p-12', type:'pronunciation', difficulty:1,
    question:'「調皮」的「調」正確讀音是？',
    options:['ㄉㄧㄠˋ','ㄊㄧㄠˊ','ㄉㄧㄠˇ','ㄊㄧㄠˋ'], answer:1,
    explanation:'「調皮」念 ㄊㄧㄠˊ（頑皮）；「調查」的「調」念 ㄉㄧㄠˋ（調動）。' },
  { id:'e-p-13', type:'pronunciation', difficulty:1,
    question:'「難過」的「難」正確讀音是？',
    options:['ㄋㄢˋ','ㄋㄢˊ','ㄋㄢ','ㄋㄢˇ'], answer:1,
    explanation:'「難過」念 ㄋㄢˊ（困難）；「苦難」的「難」念 ㄋㄢˋ（災難）。' },
  { id:'e-p-14', type:'pronunciation', difficulty:1,
    question:'「種植」的「種」正確讀音是？',
    options:['ㄓㄨㄥˇ','ㄓㄨㄥˋ','ㄓㄨㄥ','ㄔㄨㄥˋ'], answer:1,
    explanation:'「種植」念 ㄓㄨㄥˋ（動詞，栽種）；「種子」的「種」念 ㄓㄨㄥˇ（名詞）。' },
  { id:'e-p-15', type:'pronunciation', difficulty:1,
    question:'「便宜」的「便」正確讀音是？',
    options:['ㄅㄧㄢˋ','ㄆㄧㄢˊ','ㄅㄧㄢˊ','ㄆㄧㄢˋ'], answer:1,
    explanation:'「便宜」（價格低）念 ㄆㄧㄢˊ ㄧˊ；「方便」的「便」念 ㄅㄧㄢˋ。' },
  { id:'e-p-16', type:'pronunciation', difficulty:1,
    question:'「一行人」的「行」正確讀音是？',
    options:['ㄒㄧㄥˊ','ㄏㄤˊ','ㄒㄧㄥˋ','ㄏㄤˋ'], answer:1,
    explanation:'「一行人」念 ㄧ ㄏㄤˊ ㄖㄣˊ（一排、一群）；「行走」的「行」念 ㄒㄧㄥˊ。' },
  { id:'e-p-17', type:'pronunciation', difficulty:1,
    question:'「轉彎」的「轉」正確讀音是？',
    options:['ㄓㄨㄢˋ','ㄓㄨㄢˇ','ㄓㄨㄢ','ㄓㄨㄢˊ'], answer:1,
    explanation:'「轉彎」念 ㄓㄨㄢˇ（改變方向）；「轉動」的「轉」念 ㄓㄨㄢˋ（旋轉）。' },
  { id:'e-p-18', type:'pronunciation', difficulty:1,
    question:'「著急」的「著」正確讀音是？',
    options:['ㄓㄜ˙','ㄓㄨˋ','ㄓㄠˊ','ㄓㄨˊ'], answer:2,
    explanation:'「著急」念 ㄓㄠˊ（著急、著火）；「走著」的「著」念 ㄓㄜ˙（進行貌）。' },
  { id:'e-p-19', type:'pronunciation', difficulty:1,
    question:'「更衣」的「更」正確讀音是？',
    options:['ㄍㄥˋ','ㄍㄥ','ㄍㄥˊ','ㄍㄥˇ'], answer:1,
    explanation:'「更衣」念 ㄍㄥ（換衣服，動詞第一聲）；「更好」的「更」念 ㄍㄥˋ（更加）。' },
  { id:'e-p-20', type:'pronunciation', difficulty:1,
    question:'「看護」的「看」正確讀音是？',
    options:['ㄎㄢˋ','ㄎㄢ','ㄏㄢˋ','ㄏㄢ'], answer:1,
    explanation:'「看護」念 ㄎㄢ（守護、照料）；「看書」的「看」念 ㄎㄢˋ（閱覽）。' },

  // ── 字形 (23題) ───────────────
  { id:'e-f-01', type:'form', difficulty:1,
    question:'「再接再___」正確的字是？',
    options:['勵','厲','歷','礪'], answer:1,
    explanation:'「再接再厲」的「厲」指磨礪；常誤寫為「勵」（激勵）。' },
  { id:'e-f-02', type:'form', difficulty:1,
    question:'「按___就班」正確的字是？',
    options:['步','部','布','捕'], answer:1,
    explanation:'「按部就班」的「部」指部署；常誤寫為「步」（步驟）。' },
  { id:'e-f-03', type:'form', difficulty:1,
    question:'「義不容___」正確的字是？',
    options:['詞','磁','慈','辭'], answer:3,
    explanation:'「義不容辭」的「辭」指推辭；常誤寫為「詞」（詞語）。' },
  { id:'e-f-04', type:'form', difficulty:1,
    question:'「___洩情緒」正確的字是？',
    options:['渲','喧','煊','宣'], answer:3,
    explanation:'「宣洩」的「宣」指疏通散發；「渲」是渲染，意思不同。' },
  { id:'e-f-05', type:'form', difficulty:1,
    question:'「川流不___」正確的字是？',
    options:['熄','惜','昔','息'], answer:3,
    explanation:'「川流不息」的「息」指停止；「熄」是熄滅，意思不同。' },
  { id:'e-f-06', type:'form', difficulty:1,
    question:'「一___千里」正確的字是？',
    options:['洩','泄','謝','瀉'], answer:3,
    explanation:'「一瀉千里」的「瀉」形容急速奔流；「洩」是洩漏，不同。' },
  { id:'e-f-07', type:'form', difficulty:1,
    question:'「迫不___待」正確的字是？',
    options:['即','急','既','及'], answer:3,
    explanation:'「迫不及待」的「及」指趕上；常誤寫為「即」（立即）。' },
  { id:'e-f-08', type:'form', difficulty:1,
    question:'「粗___大葉」正確的字是？',
    options:['之','肢','知','枝'], answer:3,
    explanation:'「粗枝大葉」的「枝」比喻粗心；常誤寫為「肢」（肢體）。' },
  { id:'e-f-09', type:'form', difficulty:1,
    question:'「自暴自___」正確的字是？',
    options:['氣','棄','器','奇'], answer:1,
    explanation:'「自暴自棄」的「棄」指放棄；常誤寫為「氣」（氣息）。' },
  { id:'e-f-10', type:'form', difficulty:1,
    question:'「獨___一格」正確的字是？',
    options:['豎','數','術','樹'], answer:3,
    explanation:'「獨樹一格」的「樹」比喻建立風格；「豎」是豎立，不同。' },
  { id:'e-f-11', type:'form', difficulty:1,
    question:'「愁眉苦___」正確的字是？',
    options:['瞼','險','驗','臉'], answer:3,
    explanation:'「愁眉苦臉」的「臉」指面容；「瞼」是眼瞼，字形相近但不同。' },
  { id:'e-f-12', type:'form', difficulty:1,
    question:'「一___打盡」正確的字是？',
    options:['往','忘','望','網'], answer:3,
    explanation:'「一網打盡」的「網」如漁網一次捕盡；「往」是往來，不同。' },
  { id:'e-f-13', type:'form', difficulty:1,
    question:'「___心如意」正確的字是？',
    options:['成','城','誠','稱'], answer:3,
    explanation:'「稱心如意」的「稱」指符合、合意；「誠」是誠實，不同。' },
  { id:'e-f-14', type:'form', difficulty:1,
    question:'「引人入___」正確的字是？',
    options:['剩','聖','盛','勝'], answer:3,
    explanation:'「引人入勝」的「勝」指佳境；形容景色吸引人，越看越有興趣。' },
  { id:'e-f-15', type:'form', difficulty:1,
    question:'「精___求精」正確的字是？',
    options:['意','憶','藝','益'], answer:3,
    explanation:'「精益求精」的「益」指更加；形容在好的基礎上不斷追求精進。' },
  { id:'e-f-16', type:'form', difficulty:1,
    question:'「靈___一動」正確的字是？',
    options:['令','另','零','機'], answer:3,
    explanation:'「靈機一動」的「機」指機靈的念頭；形容突然想到好主意。' },
  { id:'e-f-17', type:'form', difficulty:1,
    question:'「___花一現」正確的字是？',
    options:['罈','壇','談','曇'], answer:3,
    explanation:'「曇花一現」的「曇」是曇花（短暫開放的植物）；比喻美好事物轉瞬即逝。' },
  { id:'e-f-18', type:'form', difficulty:1,
    question:'「同___共苦」正確的字是？',
    options:['感','敢','肝','甘'], answer:3,
    explanation:'「同甘共苦」的「甘」指甘甜；形容一起享樂、共同承擔困苦。' },
  { id:'e-f-19', type:'form', difficulty:1,
    question:'「走___無路」正確的字是？',
    options:['頭','透','偷','投'], answer:3,
    explanation:'「走投無路」的「投」指投奔；形容陷入絕境，無處可去。' },
  { id:'e-f-20', type:'form', difficulty:1,
    question:'「___長補短」正確的字是？',
    options:['節','結','捷','截'], answer:3,
    explanation:'「截長補短」的「截」指截取；把長的截短來補足短的，比喻彼此取長補短。' },
  { id:'e-f-21', type:'form', difficulty:1,
    question:'「人云___云」正確的字是？',
    options:['以','已','意','亦'], answer:3,
    explanation:'「人云亦云」的「亦」指也；形容沒有主見，別人說什麼就跟著說什麼。' },
  { id:'e-f-22', type:'form', difficulty:1,
    question:'「不___之客」正確的字是？',
    options:['俗','宿','熟','速'], answer:3,
    explanation:'「不速之客」的「速」原指邀請（速客=邀客）；不速之客即未受邀自行來訪的人。' },
  { id:'e-f-23', type:'form', difficulty:1,
    question:'「___雷不及掩耳」正確的字是？',
    options:['訊','信','心','迅'], answer:3,
    explanation:'「迅雷不及掩耳」的「迅」指迅速；形容行動極快，令人來不及反應。' },

  // ── 辨別正誤 (29題) ───────────
  { id:'e-t-01', type:'truefalse', difficulty:1,
    question:'「墨守成規」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「墨守成規」正確，出自墨子擅守城的典故；常誤寫為「默守成規」。' },
  { id:'e-t-02', type:'truefalse', difficulty:1,
    question:'「按步就班」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「按部就班」，「部」指部署，不是「步」（步驟）。' },
  { id:'e-t-03', type:'truefalse', difficulty:1,
    question:'「再接再勵」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「再接再厲」，「厲」指磨礪；「勵」是激勵，不同。' },
  { id:'e-t-04', type:'truefalse', difficulty:1,
    question:'「自立更生」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「自力更生」，「力」指憑自己力量；「立」是站立，不同。' },
  { id:'e-t-05', type:'truefalse', difficulty:1,
    question:'「名列前茅」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「名列前茅」正確，「茅」指古代行軍前鋒所持茅草旗，比喻名次靠前。' },
  { id:'e-t-06', type:'truefalse', difficulty:1,
    question:'「出奇致勝」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「出奇制勝」，「制」指制服壓制；「致」是導致，不同。' },
  { id:'e-t-07', type:'truefalse', difficulty:1,
    question:'「精益求精」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「精益求精」正確，「益」指更加；形容在好的基礎上繼續追求精進。' },
  { id:'e-t-08', type:'truefalse', difficulty:1,
    question:'「不速之客」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「不速之客」正確，「速」原指邀請；未受邀自行來訪的客人。' },
  { id:'e-t-09', type:'truefalse', difficulty:1,
    question:'「人云亦云」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「人云亦云」正確，「亦」指也；形容毫無主見，隨聲附和。' },
  { id:'e-t-10', type:'truefalse', difficulty:1,
    question:'「走頭無路」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「走投無路」，「投」指投奔；「頭」是頭部，不同。' },
  { id:'e-t-11', type:'truefalse', difficulty:1,
    question:'「曇花一現」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「曇花一現」正確，曇花夜晚短暫開放；比喻美好事物轉瞬即逝。' },
  { id:'e-t-12', type:'truefalse', difficulty:1,
    question:'「同甘共苦」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「同甘共苦」正確，「甘」指甘甜；形容同享快樂、共擔艱難。' },
  { id:'e-t-13', type:'truefalse', difficulty:1,
    question:'「靈機一動」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「靈機一動」正確，形容突然想到好主意。' },
  { id:'e-t-14', type:'truefalse', difficulty:1,
    question:'「半途而費」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「半途而廢」，「廢」指停止放棄；「費」是花費，不同。' },
  { id:'e-t-15', type:'truefalse', difficulty:1,
    question:'「指鹿為馬」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「指鹿為馬」正確，出自《史記》趙高故事；形容顛倒是非、蒙蔽視聽。' },
  { id:'e-t-16', type:'truefalse', difficulty:1,
    question:'「事半功倍」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「事半功倍」正確，形容付出一半努力卻得到加倍成效。' },
  { id:'e-t-17', type:'truefalse', difficulty:1,
    question:'「以逸代勞」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「以逸待勞」，「待」指等待；用安逸之師等待疲憊之敵。「代」是代替，不同。' },
  { id:'e-t-18', type:'truefalse', difficulty:1,
    question:'「鑿壁偷光」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「鑿壁偷光」正確，出自西漢匡衡故事；形容在困苦環境中刻苦讀書。' },
  { id:'e-t-19', type:'truefalse', difficulty:1,
    question:'「洗心革面」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「洗心革面」正確，「革」指改變；形容徹底悔過，重新做人。' },
  { id:'e-t-20', type:'truefalse', difficulty:1,
    question:'「望眼欲穿」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「望眼欲穿」正確，「穿」指穿透；形容期盼殷切，好像眼睛都要看穿了。' },
  { id:'e-t-21', type:'truefalse', difficulty:1,
    question:'「口若懸河」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「口若懸河」正確，「懸河」指倒掛的河流；比喻說話滔滔不絕。' },
  { id:'e-t-22', type:'truefalse', difficulty:1,
    question:'「適可而止」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「適可而止」正確，「適」指恰當；形容到了合適程度就停下，不過頭。' },
  { id:'e-t-23', type:'truefalse', difficulty:1,
    question:'「一罔打盡」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「一網打盡」，「網」如漁網一次捕盡；「罔」是欺騙、無，不同。' },
  { id:'e-t-24', type:'truefalse', difficulty:1,
    question:'「眉飛色舞」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「眉飛色舞」正確，形容得意興奮時眉眼飛動、神采飛揚的樣子。' },
  { id:'e-t-25', type:'truefalse', difficulty:1,
    question:'「唯命是從」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「唯命是從」正確，「唯」指只；形容完全服從命令，毫無異議。' },
  { id:'e-t-26', type:'truefalse', difficulty:1,
    question:'「引人入勝」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「引人入勝」正確，「勝」指佳境；形容景色或事物極有吸引力。' },
  { id:'e-t-27', type:'truefalse', difficulty:1,
    question:'「截長補短」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「截長補短」正確，「截」指截取；比喻取長補短，互相彌補不足。' },
  { id:'e-t-28', type:'truefalse', difficulty:1,
    question:'「獨樹一格」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「獨樹一格」正確，「樹」比喻建立；形容自成一種獨特的風格。' },
  { id:'e-t-29', type:'truefalse', difficulty:1,
    question:'「迫不即待」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「迫不及待」，「及」指趕上、來得及；「即」是立即，不同。' },


  // ╔══════════════════════════════╗
  // ║        中  MEDIUM  (72題)    ║
  // ╚══════════════════════════════╝

  // ── 字音 (20題) ───────────────
  { id:'m-p-01', type:'pronunciation', difficulty:2,
    question:'「角色」的「角」正確讀音是？',
    options:['ㄐㄧㄠˇ','ㄐㄩㄝˊ','ㄐㄧㄠ','ㄐㄩㄝˋ'], answer:1,
    explanation:'「角色」念 ㄐㄩㄝˊ；「角落」的「角」念 ㄐㄧㄠˇ。' },
  { id:'m-p-02', type:'pronunciation', difficulty:2,
    question:'「解剖」的「剖」正確讀音是？',
    options:['ㄆㄡˋ','ㄆㄡˇ','ㄅㄡˋ','ㄅㄡˇ'], answer:1,
    explanation:'「解剖」念 ㄆㄡˇ（第三聲）；常被誤念成第四聲。' },
  { id:'m-p-03', type:'pronunciation', difficulty:2,
    question:'「參差」的「差」正確讀音是？',
    options:['ㄔㄚ','ㄘ','ㄔㄞ','ㄘㄞ'], answer:1,
    explanation:'「參差」念 ㄘㄣ ㄘ，「差」在此念輕聲 ㄘ。' },
  { id:'m-p-04', type:'pronunciation', difficulty:2,
    question:'「似乎」的「似」正確讀音是？',
    options:['ㄕˋ','ㄙˋ','ㄕˊ','ㄙˊ'], answer:1,
    explanation:'「似乎」的「似」念 ㄙˋ；「似的」念 ㄕˋ，用法不同。' },
  { id:'m-p-05', type:'pronunciation', difficulty:2,
    question:'「暴露」的「露」正確讀音是？',
    options:['ㄌㄨˋ','ㄌㄡˋ','ㄌㄨ','ㄌㄡ'], answer:1,
    explanation:'「暴露」念 ㄌㄡˋ（顯露）；「露水」的「露」念 ㄌㄨˋ。' },
  { id:'m-p-06', type:'pronunciation', difficulty:2,
    question:'「供給」的「給」正確讀音是？',
    options:['ㄍㄟˇ','ㄍㄟˋ','ㄐㄧˇ','ㄐㄧˋ'], answer:2,
    explanation:'「供給」念 ㄐㄧˇ；「給你」的「給」念 ㄍㄟˇ（口語）。' },
  { id:'m-p-07', type:'pronunciation', difficulty:2,
    question:'「模樣」的「模」正確讀音是？',
    options:['ㄇㄛˊ','ㄇㄨˊ','ㄇㄛˋ','ㄇㄨˋ'], answer:1,
    explanation:'「模樣」念 ㄇㄨˊ；「模型」「模仿」的「模」念 ㄇㄛˊ。' },
  { id:'m-p-08', type:'pronunciation', difficulty:2,
    question:'「稽查」的「稽」正確讀音是？',
    options:['ㄑㄧˇ','ㄐㄧ','ㄒㄧ','ㄐㄧˇ'], answer:1,
    explanation:'「稽查」念 ㄐㄧ（稽留）；「稽首」才念 ㄑㄧˇ。' },
  { id:'m-p-09', type:'pronunciation', difficulty:2,
    question:'「倔強」的「強」正確讀音是？',
    options:['ㄑㄧㄤˊ','ㄑㄧㄤˇ','ㄐㄧㄤˋ','ㄐㄧㄤˇ'], answer:2,
    explanation:'「倔強」念 ㄐㄩㄝˊ ㄐㄧㄤˋ；「強大」念 ㄑㄧㄤˊ，「強迫」念 ㄑㄧㄤˇ。' },
  { id:'m-p-10', type:'pronunciation', difficulty:2,
    question:'「數落」的「數」正確讀音是？',
    options:['ㄕㄨˋ','ㄕㄨˇ','ㄕㄨ','ㄘㄨˋ'], answer:1,
    explanation:'「數落」念 ㄕㄨˇ（列舉責備）；「數學」的「數」念 ㄕㄨˋ。' },
  { id:'m-p-11', type:'pronunciation', difficulty:2,
    question:'「應付」的「應」正確讀音是？',
    options:['ㄧㄥ','ㄧㄥˋ','ㄧㄥˊ','ㄧㄥˇ'], answer:1,
    explanation:'「應付」念 ㄧㄥˋ（對付）；「應該」的「應」念 ㄧㄥ（第一聲）。' },
  { id:'m-p-12', type:'pronunciation', difficulty:2,
    question:'「處置」的「處」正確讀音是？',
    options:['ㄔㄨˋ','ㄔㄨˇ','ㄓㄨˇ','ㄓㄨˋ'], answer:1,
    explanation:'「處置」念 ㄔㄨˇ（處理，動詞）；「住處」的「處」念 ㄔㄨˋ（地方，名詞）。' },
  { id:'m-p-13', type:'pronunciation', difficulty:2,
    question:'「好惡」的「惡」正確讀音是？',
    options:['ㄜˋ','ㄨˋ','ㄜ','ㄨ'], answer:1,
    explanation:'「好惡」念 ㄏㄠˋ ㄨˋ（喜好與厭惡）；「邪惡」的「惡」念 ㄜˋ。' },
  { id:'m-p-14', type:'pronunciation', difficulty:2,
    question:'「中毒」的「中」正確讀音是？',
    options:['ㄓㄨㄥ','ㄓㄨㄥˋ','ㄓㄨㄥˇ','ㄓㄨㄥˊ'], answer:1,
    explanation:'「中毒」念 ㄓㄨㄥˋ（中了某種毒，動詞）；「中間」的「中」念 ㄓㄨㄥ。' },
  { id:'m-p-15', type:'pronunciation', difficulty:2,
    question:'「盛情」的「盛」正確讀音是？',
    options:['ㄔㄥˊ','ㄕㄥˋ','ㄔㄥˋ','ㄕㄥˊ'], answer:1,
    explanation:'「盛情」念 ㄕㄥˋ（豐盛，形容詞）；「盛飯」的「盛」念 ㄔㄥˊ（裝盛，動詞）。' },
  { id:'m-p-16', type:'pronunciation', difficulty:2,
    question:'「著重」的「著」正確讀音是？',
    options:['ㄓㄜ˙','ㄓㄠˊ','ㄓㄨˊ','ㄓㄨˋ'], answer:3,
    explanation:'「著重」念 ㄓㄨˋ（強調）；「走著」的「著」念 ㄓㄜ˙（進行貌）。' },
  { id:'m-p-17', type:'pronunciation', difficulty:2,
    question:'「差勁」的「差」正確讀音是？',
    options:['ㄔㄚ','ㄔㄞ','ㄔㄚˋ','ㄘ'], answer:2,
    explanation:'「差勁」念 ㄔㄚˋ（水準差，第四聲）；「差異」念 ㄔㄚ，「差事」念 ㄔㄞ。' },
  { id:'m-p-18', type:'pronunciation', difficulty:2,
    question:'「吐露」的「露」正確讀音是？',
    options:['ㄌㄨˋ','ㄌㄡˋ','ㄌㄨˊ','ㄌㄡˊ'], answer:1,
    explanation:'「吐露」念 ㄌㄡˋ（說出、顯露）；「露水」念 ㄌㄨˋ。' },
  { id:'m-p-19', type:'pronunciation', difficulty:2,
    question:'「解悶」的「解」正確讀音是？',
    options:['ㄐㄧㄝˋ','ㄒㄧㄝˋ','ㄐㄧㄝˇ','ㄏㄧㄝˊ'], answer:2,
    explanation:'「解悶」念 ㄐㄧㄝˇ（消解，第三聲）；「渾身解數」的「解」念 ㄒㄧㄝˋ。' },
  { id:'m-p-20', type:'pronunciation', difficulty:2,
    question:'「轉圜」的「轉」正確讀音是？',
    options:['ㄓㄨㄢˋ','ㄓㄨㄢˇ','ㄓㄨㄢ','ㄓㄨㄢˊ'], answer:1,
    explanation:'「轉圜」念 ㄓㄨㄢˇ（改變方向、斡旋）；「轉動」的「轉」念 ㄓㄨㄢˋ（旋轉）。' },

  // ── 字形 (25題) ───────────────
  { id:'m-f-01', type:'form', difficulty:2,
    question:'「___蜒」正確的字是？',
    options:['婉','腕','蜿','碗'], answer:2,
    explanation:'「蜿蜒」均為蟲字旁，形容彎曲延伸；常誤寫為「婉蜒」（女字旁）。' },
  { id:'m-f-02', type:'form', difficulty:2,
    question:'「嫉___」正確的字是？',
    options:['忌','疾','積','妒'], answer:3,
    explanation:'「嫉妒」的「妒」為女字旁；常誤寫為「嫉忌」。' },
  { id:'m-f-03', type:'form', difficulty:2,
    question:'「食不下___」正確的字是？',
    options:['咽','燕','鄢','嚥'], answer:3,
    explanation:'「食不下嚥」的「嚥」指吞嚥（ㄧㄢˋ）；「咽喉」的「咽」念 ㄧㄢ，不同。' },
  { id:'m-f-04', type:'form', difficulty:2,
    question:'「___人聽聞」正確的字是？',
    options:['害','駭','骸','孩'], answer:1,
    explanation:'「駭人聽聞」的「駭」指驚嚇；常誤寫為「害」（傷害）。' },
  { id:'m-f-05', type:'form', difficulty:2,
    question:'「再三___囑」正確的字是？',
    options:['丁','訂','釘','叮'], answer:3,
    explanation:'「叮囑」的「叮」形容反覆告誡；常誤寫為「訂」（訂購）。' },
  { id:'m-f-06', type:'form', difficulty:2,
    question:'「趁___打劫」正確的字是？',
    options:['貨','禍','伙','火'], answer:3,
    explanation:'「趁火打劫」的「火」指火災混亂；「禍」是災禍，不同。' },
  { id:'m-f-07', type:'form', difficulty:2,
    question:'「___別真假」正確的字是？',
    options:['辯','辨','辮','辭'], answer:1,
    explanation:'「辨別」的「辨」（中間是刀）指分辨識別；「辯」（中間是言）是辯論。' },
  { id:'m-f-08', type:'form', difficulty:2,
    question:'「持之以___」正確的字是？',
    options:['衡','橫','恆','杭'], answer:2,
    explanation:'「持之以恆」的「恆」指恆心常態；「衡」是平衡，「橫」是橫向，均不同。' },
  { id:'m-f-09', type:'form', difficulty:2,
    question:'「鍥而不___」正確的字是？',
    options:['舍','射','涉','捨'], answer:3,
    explanation:'「鍥而不捨」的「捨」指放棄（不放棄）；「舍」是房舍，字義不同。' },
  { id:'m-f-10', type:'form', difficulty:2,
    question:'「___己為人」正確的字是？',
    options:['舍','射','社','捨'], answer:3,
    explanation:'「捨己為人」的「捨」指捨棄；「舍」是房屋，字形相近但不同。' },
  { id:'m-f-11', type:'form', difficulty:2,
    question:'「後患無___」正確的字是？',
    options:['竟','盡','境','窮'], answer:3,
    explanation:'「後患無窮」的「窮」指窮盡沒有終止；形容遺禍不斷。' },
  { id:'m-f-12', type:'form', difficulty:2,
    question:'「___非所問」正確的字是？',
    options:['達','踏','塔','答'], answer:3,
    explanation:'「答非所問」的「答」指回答；形容回答不切合問題。' },
  { id:'m-f-13', type:'form', difficulty:2,
    question:'「膽大心___」正確的字是？',
    options:['戲','喜','洗','細'], answer:3,
    explanation:'「膽大心細」的「細」形容心思細密；「喜」是喜歡，不同。' },
  { id:'m-f-14', type:'form', difficulty:2,
    question:'「___高氣揚」正確的字是？',
    options:['指','紙','只','趾'], answer:3,
    explanation:'「趾高氣揚」的「趾」指腳趾（高抬腳步）；「指」是手指，不同。' },
  { id:'m-f-15', type:'form', difficulty:2,
    question:'「___頭喪氣」正確的字是？',
    options:['錘','捶','槌','垂'], answer:3,
    explanation:'「垂頭喪氣」的「垂」指低垂（垂下頭）；形容失意沮喪。' },
  { id:'m-f-16', type:'form', difficulty:2,
    question:'「言簡意___」正確的字是？',
    options:['蓋','該','概','賅'], answer:3,
    explanation:'「言簡意賅」的「賅」念 ㄍㄞ，指完備；形容言語簡短卻意思完整。' },
  { id:'m-f-17', type:'form', difficulty:2,
    question:'「不___而走」正確的字是？',
    options:['徑','境','競','脛'], answer:3,
    explanation:'「不脛而走」的「脛」指小腿；沒有腿卻能跑，比喻消息傳播極快。' },
  { id:'m-f-18', type:'form', difficulty:2,
    question:'「絡___不絕」正確的字是？',
    options:['易','憶','亦','繹'], answer:3,
    explanation:'「絡繹不絕」的「繹」指連續；形容人車往來接連不斷。' },
  { id:'m-f-19', type:'form', difficulty:2,
    question:'「難能可___」正確的字是？',
    options:['歸','規','鬼','貴'], answer:3,
    explanation:'「難能可貴」的「貴」指珍貴；形容難以做到之事能做到，彌足珍惜。' },
  { id:'m-f-20', type:'form', difficulty:2,
    question:'「一___莫展」正確的字是？',
    options:['愁','仇','抽','籌'], answer:3,
    explanation:'「一籌莫展」的「籌」指計策；形容一點辦法也沒有。' },
  { id:'m-f-21', type:'form', difficulty:2,
    question:'「___羽而歸」正確的字是？',
    options:['殺','煞','剎','鎩'], answer:3,
    explanation:'「鎩羽而歸」的「鎩」念 ㄕㄚ，指傷損羽毛；比喻失敗落魄地回來。' },
  { id:'m-f-22', type:'form', difficulty:2,
    question:'「___首以待」正確的字是？',
    options:['矯','橋','喬','翹'], answer:3,
    explanation:'「翹首以待」的「翹」指抬高（翹起頭來遠望）；形容殷切期盼。' },
  { id:'m-f-23', type:'form', difficulty:2,
    question:'「如___添翼」正確的字是？',
    options:['琥','戶','護','虎'], answer:3,
    explanation:'「如虎添翼」的「虎」指老虎；比喻強者更強，氣勢大增。' },
  { id:'m-f-24', type:'form', difficulty:2,
    question:'「___步自封」正確的字是？',
    options:['固','顧','鼓','故'], answer:3,
    explanation:'「故步自封」的「故」指舊有的（故步=舊有步伐）；形容守舊不求進步。' },
  { id:'m-f-25', type:'form', difficulty:2,
    question:'「汗馬___勞」正確的字是？',
    options:['工','攻','公','功'], answer:3,
    explanation:'「汗馬功勞」的「功」指功績；比喻征戰或努力的貢獻。' },

  // ── 辨別正誤 (27題) ───────────
  { id:'m-t-01', type:'truefalse', difficulty:2,
    question:'「惺惺相惜」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「惺惺相惜」正確，「惺惺」形容聰慧；指有才能的人互相欣賞。' },
  { id:'m-t-02', type:'truefalse', difficulty:2,
    question:'「渲洩情緒」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「宣洩情緒」，「宣」指疏通；「渲」是渲染，不同。' },
  { id:'m-t-03', type:'truefalse', difficulty:2,
    question:'「嘔心瀝血」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「嘔心瀝血」正確，「瀝」指一滴滴滴落；形容費盡苦心。' },
  { id:'m-t-04', type:'truefalse', difficulty:2,
    question:'「莫明其妙」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「莫名其妙」，「名」指說出（如「不可名狀」），不是「明白」的「明」。' },
  { id:'m-t-05', type:'truefalse', difficulty:2,
    question:'「完璧歸趙」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「完璧歸趙」正確，「璧」是圓形玉器（和氏璧）；常誤寫為「壁」（牆壁）。' },
  { id:'m-t-06', type:'truefalse', difficulty:2,
    question:'「破斧沉舟」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「破釜沉舟」，「釜」是鍋子；「斧」是斧頭，不同。' },
  { id:'m-t-07', type:'truefalse', difficulty:2,
    question:'「好高鶩遠」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「好高騖遠」，「騖」（馬字旁）指馬奔馳；「鶩」（鳥字旁）是野鴨，用於「趨之若鶩」。' },
  { id:'m-t-08', type:'truefalse', difficulty:2,
    question:'「持之以恆」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「持之以恆」正確，形容做事有恆心，持續不懈。' },
  { id:'m-t-09', type:'truefalse', difficulty:2,
    question:'「趾高氣揚」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「趾高氣揚」正確，「趾」是腳趾；形容得意驕傲的樣子。' },
  { id:'m-t-10', type:'truefalse', difficulty:2,
    question:'「垂頭喪氣」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「垂頭喪氣」正確，「垂」指低垂；形容失意沮喪的神情。' },
  { id:'m-t-11', type:'truefalse', difficulty:2,
    question:'「精義求精」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「精益求精」，「益」指更加；「義」是道義，不同。' },
  { id:'m-t-12', type:'truefalse', difficulty:2,
    question:'「一籌莫展」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「一籌莫展」正確，「籌」是計策；形容毫無辦法，束手無策。' },
  { id:'m-t-13', type:'truefalse', difficulty:2,
    question:'「不徑而走」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「不脛而走」，「脛」是小腿；沒有腿卻能行，比喻傳播極快。「徑」是小路，不同。' },
  { id:'m-t-14', type:'truefalse', difficulty:2,
    question:'「言簡意賅」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「言簡意賅」正確，「賅」念 ㄍㄞ，指完備；形容語言簡短而意思完整。' },
  { id:'m-t-15', type:'truefalse', difficulty:2,
    question:'「絡繹不絕」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「絡繹不絕」正確，「繹」指連續；形容人車接連不斷。' },
  { id:'m-t-16', type:'truefalse', difficulty:2,
    question:'「難能可貴」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「難能可貴」正確，形容難以做到的事能做到，彌足珍貴。' },
  { id:'m-t-17', type:'truefalse', difficulty:2,
    question:'「鎩羽而歸」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「鎩羽而歸」正確，「鎩」念 ㄕㄚ，指摧折羽毛；比喻失敗落魄地歸來。' },
  { id:'m-t-18', type:'truefalse', difficulty:2,
    question:'「故步自封」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「故步自封」正確，「故步」指舊有步伐；形容守舊自限，不求進步。' },
  { id:'m-t-19', type:'truefalse', difficulty:2,
    question:'「如虎填翼」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「如虎添翼」，「添」是增添；「填」是填充，不同。' },
  { id:'m-t-20', type:'truefalse', difficulty:2,
    question:'「捨己為人」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「捨己為人」正確，「捨」指捨棄自身利益；注意「捨」非「舍」（房舍）。' },
  { id:'m-t-21', type:'truefalse', difficulty:2,
    question:'「後患無窮」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「後患無窮」正確，「窮」指窮盡；形容遺留的禍患沒有終止。' },
  { id:'m-t-22', type:'truefalse', difficulty:2,
    question:'「名副其實」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「名副其實」正確，「副」指符合；形容名聲與實際相符。' },
  { id:'m-t-23', type:'truefalse', difficulty:2,
    question:'「心猿意馬」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「心猿意馬」正確，「猿馬」比喻心思難以約束；形容心神不定。' },
  { id:'m-t-24', type:'truefalse', difficulty:2,
    question:'「口是心非」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「口是心非」正確，形容嘴上說的與心裡想的完全相反。' },
  { id:'m-t-25', type:'truefalse', difficulty:2,
    question:'「置之度外」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「置之度外」正確，「度」指考慮；形容完全不放在心上、不予計較。' },
  { id:'m-t-26', type:'truefalse', difficulty:2,
    question:'「突飛猛晉」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「突飛猛進」，「進」指進步前進；「晉」是晉升，不同。' },
  { id:'m-t-27', type:'truefalse', difficulty:2,
    question:'「汗馬功勞」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「汗馬功勞」正確，「汗馬」指征戰中的馬匹流汗；比喻努力奮鬥的功績。' },


  // ╔══════════════════════════════╗
  // ║          難  HARD  (57題)    ║
  // ╚══════════════════════════════╝

  // ── 字音 (20題) ───────────────
  { id:'h-p-01', type:'pronunciation', difficulty:3,
    question:'「齷齪」的「齪」正確讀音是？',
    options:['ㄔㄨˊ','ㄘㄨˋ','ㄓㄨㄛˊ','ㄘㄨˊ'], answer:1,
    explanation:'「齷齪」念 ㄨㄛˋ ㄘㄨˋ，形容骯髒或卑劣。兩字均為齒字旁。' },
  { id:'h-p-02', type:'pronunciation', difficulty:3,
    question:'「逡巡」的「逡」正確讀音是？',
    options:['ㄓㄨㄣ','ㄔㄨㄣ','ㄑㄩㄣ','ㄒㄩㄣ'], answer:2,
    explanation:'「逡巡」念 ㄑㄩㄣ ㄒㄩㄣˊ，指因顧慮而徘徊不前。' },
  { id:'h-p-03', type:'pronunciation', difficulty:3,
    question:'「橫行霸道」的「橫」正確讀音是？',
    options:['ㄏㄥˊ','ㄏㄥˋ','ㄏㄨㄤˊ','ㄏㄨㄤˋ'], answer:1,
    explanation:'「橫行霸道」的「橫」念 ㄏㄥˋ（蠻橫）；「橫線」的「橫」念 ㄏㄥˊ。' },
  { id:'h-p-04', type:'pronunciation', difficulty:3,
    question:'「齟齬」的「齟」正確讀音是？',
    options:['ㄓㄨˇ','ㄐㄩˇ','ㄑㄩˇ','ㄔㄨˇ'], answer:1,
    explanation:'「齟齬」念 ㄐㄩˇ ㄩˇ，原指牙齒不對齊，引申為意見不合。' },
  { id:'h-p-05', type:'pronunciation', difficulty:3,
    question:'「瞠目結舌」的「瞠」正確讀音是？',
    options:['ㄓㄥ','ㄊㄤ','ㄔㄥ','ㄔㄤ'], answer:3,
    explanation:'「瞠目結舌」的「瞠」念 ㄔㄤ，指睜大眼睛直視。' },
  { id:'h-p-06', type:'pronunciation', difficulty:3,
    question:'「拈花惹草」的「拈」正確讀音是？',
    options:['ㄓㄢ','ㄓㄢˋ','ㄑㄧㄢ','ㄋㄧㄢ'], answer:3,
    explanation:'「拈花惹草」的「拈」念 ㄋㄧㄢ，指用指輕取；常因字形似「沾」而誤念 ㄓㄢ。' },
  { id:'h-p-07', type:'pronunciation', difficulty:3,
    question:'「悖論」的「悖」正確讀音是？',
    options:['ㄆㄟˋ','ㄅㄟ','ㄆㄟ','ㄅㄟˋ'], answer:3,
    explanation:'「悖論」念 ㄅㄟˋ，「悖」指違背矛盾（悖理、悖謬）。' },
  { id:'h-p-08', type:'pronunciation', difficulty:3,
    question:'「惝恍」的「惝」正確讀音是？',
    options:['ㄊㄤˇ','ㄔㄤˋ','ㄊㄤ','ㄔㄤˇ'], answer:3,
    explanation:'「惝恍」念 ㄔㄤˇ ㄏㄨㄤˇ，形容精神恍惚、神智不清的樣子。' },
  { id:'h-p-09', type:'pronunciation', difficulty:3,
    question:'「噤若寒蟬」的「噤」正確讀音是？',
    options:['ㄑㄧㄣˋ','ㄐㄧㄣˋ','ㄑㄧㄣ','ㄐㄧㄣ'], answer:1,
    explanation:'「噤若寒蟬」念 ㄐㄧㄣˋ，「噤」指閉口不言；形容不敢開口說話。' },
  { id:'h-p-10', type:'pronunciation', difficulty:3,
    question:'「咫尺天涯」的「咫」正確讀音是？',
    options:['ㄓˋ','ㄓˇ','ㄓ','ㄓˊ'], answer:1,
    explanation:'「咫尺」念 ㄓˇ ㄔˇ，「咫」是古代長度單位，念第三聲；形容距離極近。' },
  { id:'h-p-11', type:'pronunciation', difficulty:3,
    question:'「殞命」的「殞」正確讀音是？',
    options:['ㄩㄣˋ','ㄩㄣˇ','ㄩㄣ','ㄩㄢˇ'], answer:1,
    explanation:'「殞命」念 ㄩㄣˇ ㄇㄧㄥˋ，「殞」指死亡、墜落，念第三聲。' },
  { id:'h-p-12', type:'pronunciation', difficulty:3,
    question:'「蟄伏」的「蟄」正確讀音是？',
    options:['ㄓˊ','ㄓㄜˊ','ㄔˊ','ㄔㄜˊ'], answer:1,
    explanation:'「蟄伏」念 ㄓㄜˊ ㄈㄨˊ，「蟄」指蟲類冬眠；引申為潛伏待機。' },
  { id:'h-p-13', type:'pronunciation', difficulty:3,
    question:'「窺伺」的「伺」正確讀音是？',
    options:['ㄘˋ','ㄙˋ','ㄘ','ㄙ'], answer:1,
    explanation:'「窺伺」念 ㄎㄨㄟ ㄙˋ（伺機）；「伺候」的「伺」念 ㄘˋ（服侍），兩者不同。' },
  { id:'h-p-14', type:'pronunciation', difficulty:3,
    question:'「詰問」的「詰」正確讀音是？',
    options:['ㄑㄧㄝˊ','ㄐㄩˊ','ㄑㄩㄝˊ','ㄐㄧㄝˊ'], answer:3,
    explanation:'「詰問」念 ㄐㄧㄝˊ ㄨㄣˋ，「詰」指追問責問。' },
  { id:'h-p-15', type:'pronunciation', difficulty:3,
    question:'「訕笑」的「訕」正確讀音是？',
    options:['ㄕㄢ','ㄕㄢˋ','ㄒㄧㄢ','ㄒㄧㄢˋ'], answer:1,
    explanation:'「訕笑」念 ㄕㄢˋ ㄒㄧㄠˋ，「訕」指嘲笑、訕訕，念第四聲。' },
  { id:'h-p-16', type:'pronunciation', difficulty:3,
    question:'「嗤之以鼻」的「嗤」正確讀音是？',
    options:['ㄓ','ㄔ','ㄘ','ㄕ'], answer:1,
    explanation:'「嗤之以鼻」的「嗤」念 ㄔ（第一聲），指輕視嘲笑。' },
  { id:'h-p-17', type:'pronunciation', difficulty:3,
    question:'「凜冽」的「凜」正確讀音是？',
    options:['ㄌㄧㄣˋ','ㄌㄧㄣˇ','ㄌㄧㄣ','ㄌㄧㄣˊ'], answer:1,
    explanation:'「凜冽」念 ㄌㄧㄣˇ ㄌㄧㄝˋ，「凜」表示寒冷嚴肅，念第三聲。' },
  { id:'h-p-18', type:'pronunciation', difficulty:3,
    question:'「窸窣」的「窸」正確讀音是？',
    options:['ㄒㄧˊ','ㄒㄧ','ㄒㄧˋ','ㄒㄩ'], answer:1,
    explanation:'「窸窣」念 ㄒㄧ ㄙㄨ，形容細微的摩擦聲響。' },
  { id:'h-p-19', type:'pronunciation', difficulty:3,
    question:'「桀驁不馴」的「驁」正確讀音是？',
    options:['ㄧㄠˋ','ㄠˋ','ㄠ','ㄧㄠ'], answer:1,
    explanation:'「桀驁不馴」的「驁」念 ㄠˋ，指驁悍不受約束。' },
  { id:'h-p-20', type:'pronunciation', difficulty:3,
    question:'「顢頇」的「顢」正確讀音是？',
    options:['ㄇㄢˇ','ㄇㄢˊ','ㄇㄢˋ','ㄇㄢ'], answer:1,
    explanation:'「顢頇」念 ㄇㄢˊ ㄏㄢ，形容辦事糊塗不負責任的樣子。' },

  // ── 字形 (20題) ───────────────
  { id:'h-f-01', type:'form', difficulty:3,
    question:'「___竹難書」正確的字是？',
    options:['磬','磐','罄','聲'], answer:2,
    explanation:'「罄竹難書」的「罄」指竭盡；常誤寫為「磬」（打擊樂器）。' },
  { id:'h-f-02', type:'form', difficulty:3,
    question:'「___躇滿志」正確的字是？',
    options:['疇','籌','躊','酬'], answer:2,
    explanation:'「躊躇滿志」的「躊」為足字旁，形容得意洋洋。' },
  { id:'h-f-03', type:'form', difficulty:3,
    question:'「不___思索」正確的字是？',
    options:['加','家','架','假'], answer:3,
    explanation:'「不假思索」的「假」念 ㄐㄧㄚˋ，指憑藉借助；不是「增加」的「加」。' },
  { id:'h-f-04', type:'form', difficulty:3,
    question:'「一___不苟」正確的字是？',
    options:['思','私','斯','絲'], answer:3,
    explanation:'「一絲不苟」的「絲」指極細微；形容連一絲一毫都不馬虎。' },
  { id:'h-f-05', type:'form', difficulty:3,
    question:'「___沙成塔」正確的字是？',
    options:['積','集','居','聚'], answer:3,
    explanation:'「聚沙成塔」的「聚」指聚集；比喻積少成多，集腋成裘。' },
  { id:'h-f-06', type:'form', difficulty:3,
    question:'「鞭___入裡」正確的字是？',
    options:['僻','辟','闢','避'], answer:1,
    explanation:'「鞭辟入裡」的「辟」念 ㄆㄧˋ，指打開深入；形容分析透徹入裡。' },
  { id:'h-f-07', type:'form', difficulty:3,
    question:'「濫___充數」正確的字是？',
    options:['藍','攔','嵐','竽'], answer:3,
    explanation:'「濫竽充數」的「竽」是古代吹奏樂器；出自《韓非子》，比喻以次充好。' },
  { id:'h-f-08', type:'form', difficulty:3,
    question:'「___氣凌人」正確的字是？',
    options:['剩','聖','勝','盛'], answer:3,
    explanation:'「盛氣凌人」的「盛」指旺盛氣焰；形容傲慢自大，以氣勢壓人。' },
  { id:'h-f-09', type:'form', difficulty:3,
    question:'「束___就擒」正確的字是？',
    options:['速','宿','縮','手'], answer:3,
    explanation:'「束手就擒」的「手」是手部；意指雙手被縛，甘願被捉拿。' },
  { id:'h-f-10', type:'form', difficulty:3,
    question:'「一___千金」正確的字是？',
    options:['鍋','鑼','落','諾'], answer:3,
    explanation:'「一諾千金」的「諾」指承諾；形容言而有信，承諾重如千金。' },
  { id:'h-f-11', type:'form', difficulty:3,
    question:'「___綜複雜」正確的字是？',
    options:['厝','措','挫','錯'], answer:3,
    explanation:'「錯綜複雜」的「錯」指交錯；形容情況複雜頭緒繁多。' },
  { id:'h-f-12', type:'form', difficulty:3,
    question:'「掩___盜鈴」正確的字是？',
    options:['爾','貳','二','耳'], answer:3,
    explanation:'「掩耳盜鈴」的「耳」指耳朵；出自《呂氏春秋》，比喻自欺欺人。' },
  { id:'h-f-13', type:'form', difficulty:3,
    question:'「臥薪___膽」正確的字是？',
    options:['償','常','廠','嘗'], answer:3,
    explanation:'「臥薪嘗膽」的「嘗」指品嚐；出自越王勾踐故事，形容刻苦自勵以雪恥。' },
  { id:'h-f-14', type:'form', difficulty:3,
    question:'「千___一髮」正確的字是？',
    options:['均','君','軍','鈞'], answer:3,
    explanation:'「千鈞一髮」的「鈞」是古代重量單位（三十斤）；千鈞懸於一髮，形容極度危急。' },
  { id:'h-f-15', type:'form', difficulty:3,
    question:'「強___奪理」正確的字是？',
    options:['搶','槍','羌','詞'], answer:3,
    explanation:'「強詞奪理」的「詞」指言詞；形容沒有道理卻硬要辯論，歪曲道理。' },
  { id:'h-f-16', type:'form', difficulty:3,
    question:'「前___後恭」正確的字是？',
    options:['居','拒','巨','倨'], answer:3,
    explanation:'「前倨後恭」的「倨」念 ㄐㄩˋ，指傲慢；形容先前傲慢後來恭敬，態度大轉變。' },
  { id:'h-f-17', type:'form', difficulty:3,
    question:'「萬___不復」正確的字是？',
    options:['結','截','竭','劫'], answer:3,
    explanation:'「萬劫不復」的「劫」指劫難；形容陷入絕境，永遠無法恢復。' },
  { id:'h-f-18', type:'form', difficulty:3,
    question:'「功虧一___」正確的字是？',
    options:['潰','匱','饋','簣'], answer:3,
    explanation:'「功虧一簣」的「簣」念 ㄎㄨㄟˋ，是裝土的竹筐；差一筐土而失敗，比喻功敗垂成。' },
  { id:'h-f-19', type:'form', difficulty:3,
    question:'「___目結舌」正確的字是？',
    options:['張','睜','撐','瞠'], answer:3,
    explanation:'「瞠目結舌」的「瞠」念 ㄔㄤ，指睜大眼睛直視；形容驚訝得說不出話。' },
  { id:'h-f-20', type:'form', difficulty:3,
    question:'「___絲馬跡」正確的字是？',
    options:['珠','株','朱','蛛'], answer:3,
    explanation:'「蛛絲馬跡」的「蛛」是蜘蛛；比喻可循的隱約線索和痕跡。' },

  // ── 辨別正誤 (17題) ───────────
  { id:'h-t-01', type:'truefalse', difficulty:3,
    question:'「罄竹難書」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「罄竹難書」正確，「罄」指竭盡；竹子用完也寫不完，比喻罪惡極多。' },
  { id:'h-t-02', type:'truefalse', difficulty:3,
    question:'「不假思索」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「不假思索」正確，「假」指憑藉借助；常誤寫為「不加思索」。' },
  { id:'h-t-03', type:'truefalse', difficulty:3,
    question:'「甘敗下風」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「甘拜下風」，「拜」指拜服；「敗」是失敗，不同。' },
  { id:'h-t-04', type:'truefalse', difficulty:3,
    question:'「趨之若鶩」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「趨之若鶩」正確，「鶩」（鳥旁）是野鴨；「騖」（馬旁）用於「好高騖遠」。' },
  { id:'h-t-05', type:'truefalse', difficulty:3,
    question:'「挺而走險」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「鋌而走險」，「鋌」念 ㄊㄧㄥˋ，指快跑；「挺」是挺直，不同。' },
  { id:'h-t-06', type:'truefalse', difficulty:3,
    question:'「噤若寒蟬」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「噤若寒蟬」正確，「噤」指閉口；寒蟬深秋不鳴，比喻不敢開口說話。' },
  { id:'h-t-07', type:'truefalse', difficulty:3,
    question:'「一諾千金」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「一諾千金」正確，「諾」指承諾；形容信守承諾，說話算數。' },
  { id:'h-t-08', type:'truefalse', difficulty:3,
    question:'「前倨後恭」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「前倨後恭」正確，「倨」念 ㄐㄩˋ，指傲慢；形容先傲後謙，態度大轉變。' },
  { id:'h-t-09', type:'truefalse', difficulty:3,
    question:'「千鈞一髮」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「千鈞一髮」正確，「鈞」是古代重量單位；形容情況極度危急。' },
  { id:'h-t-10', type:'truefalse', difficulty:3,
    question:'「鞭辟入理」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「鞭辟入裡」，「裡」指內部深處；「理」是道理，不同。' },
  { id:'h-t-11', type:'truefalse', difficulty:3,
    question:'「濫竽充數」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「濫竽充數」正確，「竽」是古代樂器；出自《韓非子》，比喻以次充好虛佔其位。' },
  { id:'h-t-12', type:'truefalse', difficulty:3,
    question:'「盛氣凌人」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「盛氣凌人」正確，「盛」指旺盛氣焰；形容傲慢自大，以氣勢壓制他人。' },
  { id:'h-t-13', type:'truefalse', difficulty:3,
    question:'「功虧一匱」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「功虧一簣」，「簣」（ㄎㄨㄟˋ）是裝土竹筐；「匱」是缺乏，不同。' },
  { id:'h-t-14', type:'truefalse', difficulty:3,
    question:'「嗤之以鼻」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「嗤之以鼻」正確，「嗤」念 ㄔ，指輕蔑嘲笑；用鼻子哼氣表示鄙視。' },
  { id:'h-t-15', type:'truefalse', difficulty:3,
    question:'「強詞奪理」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「強詞奪理」正確，「強」念 ㄑㄧㄤˇ；形容沒有道理卻硬要辯論。' },
  { id:'h-t-16', type:'truefalse', difficulty:3,
    question:'「萬劫不復」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「萬劫不復」正確，「劫」指劫難；形容陷入絕境，永遠無法恢復。' },
  { id:'h-t-17', type:'truefalse', difficulty:3,
    question:'「蛛絲螞跡」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「蛛絲馬跡」，「馬跡」是馬蹄印；「螞」是螞蟻，不同。' },

  // ── Easy Pronunciation 21-40 ──────────────────────────
  { id:'e-p-21', type:'pronunciation', difficulty:1,
    question:'「傳統」的「傳」應該怎麼念？',
    options:['ㄔㄨㄢˊ','ㄓㄨㄢˋ','ㄔㄨㄢˋ','ㄓㄨㄢˊ'], answer:0,
    explanation:'「傳統」的「傳」念 ㄔㄨㄢˊ（流傳）；「傳記」的「傳」才念 ㄓㄨㄢˋ。' },
  { id:'e-p-22', type:'pronunciation', difficulty:1,
    question:'「會計」的「會」應該怎麼念？',
    options:['ㄏㄨㄟˋ','ㄎㄨㄞˋ','ㄏㄨㄟˊ','ㄎㄨㄞˊ'], answer:1,
    explanation:'「會計」的「會」念 ㄎㄨㄞˋ，是專業術語讀法；一般「開會」才念 ㄏㄨㄟˋ。' },
  { id:'e-p-23', type:'pronunciation', difficulty:1,
    question:'「薄荷」的「薄」應該怎麼念？',
    options:['ㄅㄛˊ','ㄅㄠˊ','ㄅㄛˋ','ㄆㄛˊ'], answer:2,
    explanation:'「薄荷」的「薄」念 ㄅㄛˋ，是植物專名；「薄弱」的「薄」念 ㄅㄛˊ。' },
  { id:'e-p-24', type:'pronunciation', difficulty:1,
    question:'「血液」的「血」應該怎麼念？',
    options:['ㄒㄧㄝˇ','ㄒㄩㄝˇ','ㄒㄧㄝˋ','ㄒㄩㄝˋ'], answer:1,
    explanation:'「血液」念 ㄒㄩㄝˇ；單獨用或口語中「流血」可念 ㄒㄧㄝˇ。' },
  { id:'e-p-25', type:'pronunciation', difficulty:1,
    question:'「角色」的「角」應該怎麼念？',
    options:['ㄐㄧㄠˇ','ㄐㄩㄝˊ','ㄐㄧㄠ','ㄐㄩㄝˋ'], answer:1,
    explanation:'「角色」的「角」念 ㄐㄩㄝˊ；「角落」的「角」念 ㄐㄧㄠˇ。' },
  { id:'e-p-26', type:'pronunciation', difficulty:1,
    question:'「參考」的「參」應該怎麼念？',
    options:['ㄘㄢ','ㄕㄣ','ㄘㄣ','ㄙㄢ'], answer:0,
    explanation:'「參考」念 ㄘㄢ；「人參」念 ㄕㄣ；「參差」念 ㄘㄣ。' },
  { id:'e-p-27', type:'pronunciation', difficulty:1,
    question:'「行李」的「行」應該怎麼念？',
    options:['ㄒㄧㄥˊ','ㄏㄤˊ','ㄒㄧㄥˋ','ㄏㄤˋ'], answer:0,
    explanation:'「行李」念 ㄒㄧㄥˊ；「銀行」念 ㄏㄤˊ。' },
  { id:'e-p-28', type:'pronunciation', difficulty:1,
    question:'「空間」的「空」應該怎麼念？',
    options:['ㄎㄨㄥˋ','ㄎㄨㄥ','ㄏㄨㄥ','ㄎㄨㄥˊ'], answer:1,
    explanation:'「空間」念 ㄎㄨㄥ（陰平）；「空白」念 ㄎㄨㄥˋ表示沒有填滿。' },
  { id:'e-p-29', type:'pronunciation', difficulty:1,
    question:'「好奇」的「好」應該怎麼念？',
    options:['ㄏㄠˇ','ㄏㄠˋ','ㄏㄠ','ㄏㄠˊ'], answer:1,
    explanation:'「好奇」念 ㄏㄠˋ（喜好）；「好人」念 ㄏㄠˇ（良善）。' },
  { id:'e-p-30', type:'pronunciation', difficulty:1,
    question:'「重量」的「重」應該怎麼念？',
    options:['ㄔㄨㄥˊ','ㄓㄨㄥˋ','ㄓㄨㄥˊ','ㄔㄨㄥˋ'], answer:1,
    explanation:'「重量」念 ㄓㄨㄥˋ（分量）；「重複」念 ㄔㄨㄥˊ（再次）。' },
  { id:'e-p-31', type:'pronunciation', difficulty:1,
    question:'「長輩」的「長」應該怎麼念？',
    options:['ㄔㄤˊ','ㄓㄤˇ','ㄔㄤˇ','ㄓㄤˊ'], answer:1,
    explanation:'「長輩」念 ㄓㄤˇ（年紀大的）；「長度」念 ㄔㄤˊ（長短）。' },
  { id:'e-p-32', type:'pronunciation', difficulty:1,
    question:'「音樂」的「樂」應該怎麼念？',
    options:['ㄌㄜˋ','ㄩㄝˋ','ㄌㄜ','ㄩㄝˊ'], answer:1,
    explanation:'「音樂」念 ㄩㄝˋ；「快樂」念 ㄌㄜˋ。' },
  { id:'e-p-33', type:'pronunciation', difficulty:1,
    question:'「大夫」（醫生）的「大」應該怎麼念？',
    options:['ㄉㄚˋ','ㄉㄞˋ','ㄊㄞˋ','ㄊㄚˋ'], answer:1,
    explanation:'「大夫」（醫生）念 ㄉㄞˋ；「大學」才念 ㄉㄚˋ。' },
  { id:'e-p-34', type:'pronunciation', difficulty:1,
    question:'「假日」的「假」應該怎麼念？',
    options:['ㄐㄧㄚˇ','ㄐㄧㄚˋ','ㄐㄧㄚ','ㄍㄚˋ'], answer:1,
    explanation:'「假日」念 ㄐㄧㄚˋ（休假）；「假裝」念 ㄐㄧㄚˇ（虛假）。' },
  { id:'e-p-35', type:'pronunciation', difficulty:1,
    question:'「調查」的「調」應該怎麼念？',
    options:['ㄉㄧㄠˋ','ㄊㄧㄠˊ','ㄉㄧㄠ','ㄊㄧㄠˋ'], answer:0,
    explanation:'「調查」念 ㄉㄧㄠˋ；「調節」念 ㄊㄧㄠˊ。' },
  { id:'e-p-36', type:'pronunciation', difficulty:1,
    question:'「說服」的「服」應該怎麼念？',
    options:['ㄈㄨˊ','ㄈㄨˋ','ㄅㄨˊ','ㄅㄨˋ'], answer:1,
    explanation:'「說服」的「服」念 ㄈㄨˋ；「衣服」念 ㄈㄨˊ。' },
  { id:'e-p-37', type:'pronunciation', difficulty:1,
    question:'「地殼」的「殼」應該怎麼念？',
    options:['ㄎㄜˊ','ㄑㄧㄠˋ','ㄎㄜˋ','ㄑㄧㄠ'], answer:1,
    explanation:'「地殼」念 ㄑㄧㄠˋ；「貝殼」念 ㄎㄜˊ。' },
  { id:'e-p-38', type:'pronunciation', difficulty:1,
    question:'「著作」的「著」應該怎麼念？',
    options:['ㄓㄜˊ','ㄓㄨˋ','ㄓㄨㄛˊ','ㄓㄠ'], answer:1,
    explanation:'「著作」念 ㄓㄨˋ；「著急」念 ㄓㄠˊ；「穿著」念 ㄓㄨㄛˊ。' },
  { id:'e-p-39', type:'pronunciation', difficulty:1,
    question:'「分析」的「析」應該怎麼念？',
    options:['ㄒㄧˊ','ㄒㄧ','ㄒㄧˇ','ㄒㄧˋ'], answer:1,
    explanation:'「分析」的「析」念 ㄒㄧ（陰平）；不要念成去聲 ㄒㄧˋ。' },
  { id:'e-p-40', type:'pronunciation', difficulty:1,
    question:'「蒞臨」的「蒞」應該怎麼念？',
    options:['ㄌㄧˋ','ㄌㄧˊ','ㄌㄧˇ','ㄌㄧ'], answer:0,
    explanation:'「蒞臨」的「蒞」念 ㄌㄧˋ，表示到場；與「立」同音。' },

  // ── Easy Form 24-43 ──────────────────────────────────
  { id:'e-f-24', type:'form', difficulty:1,
    question:'「再接再____」，空格應填入哪個字？',
    options:['勵','厲','力','歷'], answer:1,
    explanation:'「再接再厲」，「厲」是磨刀石，引申為奮勉。常被誤寫為「勵」（勉勵）。' },
  { id:'e-f-25', type:'form', difficulty:1,
    question:'「出____不意」，空格應填入哪個字？',
    options:['忽','乎','呼','虎'], answer:1,
    explanation:'「出乎不意」？實為「出其不意」，「其」指對方，趁對方不注意時行動。' },
  { id:'e-f-26', type:'form', difficulty:1,
    question:'「精神____鑠」，空格應填入哪個字？',
    options:['礫','爍','鑠','矍'], answer:2,
    explanation:'「精神矍鑠」，「矍」（ㄐㄩㄝˊ）「鑠」（ㄕㄨㄛˋ），形容老人精神健旺。' },
  { id:'e-f-27', type:'form', difficulty:1,
    question:'「天____地義」，空格應填入哪個字？',
    options:['荒','慌','經','常'], answer:2,
    explanation:'「天經地義」，「經」指常道；形容理所當然，不容置疑。' },
  { id:'e-f-28', type:'form', difficulty:1,
    question:'「____然大悟」，空格應填入哪個字？',
    options:['恍','晃','謊','慌'], answer:0,
    explanation:'「恍然大悟」，「恍」（ㄏㄨㄤˇ）有忽然醒悟之意。' },
  { id:'e-f-29', type:'form', difficulty:1,
    question:'「____耳盜鈴」，空格應填入哪個字？',
    options:['掩','淹','嚴','燕'], answer:0,
    explanation:'「掩耳盜鈴」，「掩」是遮蓋；比喻自欺欺人。' },
  { id:'e-f-30', type:'form', difficulty:1,
    question:'「勤能補____」，空格應填入哪個字？',
    options:['拙','桌','卓','捉'], answer:0,
    explanation:'「勤能補拙」，「拙」（ㄓㄨㄛˊ）指笨拙；勤奮可以彌補天資不足。' },
  { id:'e-f-31', type:'form', difficulty:1,
    question:'「____若木雞」，空格應填入哪個字？',
    options:['呆','待','代','戴'], answer:0,
    explanation:'「呆若木雞」，「呆」形容發愣；形容人驚嚇或發呆的樣子。' },
  { id:'e-f-32', type:'form', difficulty:1,
    question:'「鬼____神差」，空格應填入哪個字？',
    options:['使','事','始','士'], answer:0,
    explanation:'「鬼使神差」，「使」是差遣；形容事情的發生好像有神鬼的驅使。' },
  { id:'e-f-33', type:'form', difficulty:1,
    question:'「半途而____」，空格應填入哪個字？',
    options:['費','廢','廢','肺'], answer:1,
    explanation:'「半途而廢」，「廢」是放棄；中途停止，不能堅持到底。' },
  { id:'e-f-34', type:'form', difficulty:1,
    question:'「欲____故縱」，空格應填入哪個字？',
    options:['擒','禽','欽','芹'], answer:0,
    explanation:'「欲擒故縱」，「擒」（ㄑㄧㄣˊ）是捉拿；先放鬆再捉拿的策略。' },
  { id:'e-f-35', type:'form', difficulty:1,
    question:'「海市____樓」，空格應填入哪個字？',
    options:['深','神','蜃','甚'], answer:2,
    explanation:'「海市蜃樓」，「蜃」（ㄕㄣˋ）是大蛤蜊；指虛幻不實的景象。' },
  { id:'e-f-36', type:'form', difficulty:1,
    question:'「一____千里」，空格應填入哪個字？',
    options:['望','忘','旺','網'], answer:0,
    explanation:'「一望千里」，「望」是遠看；形容地勢開闊，視野廣遠。' },
  { id:'e-f-37', type:'form', difficulty:1,
    question:'「愁眉____臉」，空格應填入哪個字？',
    options:['苦','哭','枯','庫'], answer:0,
    explanation:'「愁眉苦臉」，「苦」指痛苦；形容憂愁、痛苦的表情。' },
  { id:'e-f-38', type:'form', difficulty:1,
    question:'「一帆風____」，空格應填入哪個字？',
    options:['順','順','尚','尚'], answer:0,
    explanation:'「一帆風順」，「順」表示順利；比喻非常順利，沒有阻礙。' },

  // ── Easy Truefalse 30-48 ───────────────────────────────
  { id:'e-t-30', type:'truefalse', difficulty:1,
    question:'「如火如荼」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「如火如荼」正確，「荼」（ㄊㄨˊ）是白色的茅草花；形容聲勢盛大。' },
  { id:'e-t-31', type:'truefalse', difficulty:1,
    question:'「再接再勵」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「再接再厲」，「厲」是磨刀石，引申奮勉；「勵」是勉勵，字不同。' },
  { id:'e-t-32', type:'truefalse', difficulty:1,
    question:'「得意忘形」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「得意忘形」正確，形容因高興而忘了自己的言行舉止。' },
  { id:'e-t-33', type:'truefalse', difficulty:1,
    question:'「漫不今心」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「漫不經心」，「經心」是放在心上；粗心大意的意思。' },
  { id:'e-t-34', type:'truefalse', difficulty:1,
    question:'「一鼓作氣」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「一鼓作氣」正確，「一鼓」指第一次擊鼓；比喻趁勢振作，一舉成功。' },
  { id:'e-t-35', type:'truefalse', difficulty:1,
    question:'「按步就班」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「按部就班」，「部」指部署；依照規定步驟行事。' },
  { id:'e-t-36', type:'truefalse', difficulty:1,
    question:'「無微不至」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「無微不至」正確，形容關懷周到，細緻入微。' },
  { id:'e-t-37', type:'truefalse', difficulty:1,
    question:'「雕樑畫壁」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「雕樑畫棟」，「棟」指屋脊大梁；形容建築裝飾華麗。' },
  { id:'e-t-38', type:'truefalse', difficulty:1,
    question:'「千鈞一髮」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「千鈞一髮」正確，「鈞」為古代重量單位；形容極度危險的情況。' },
  { id:'e-t-39', type:'truefalse', difficulty:1,
    question:'「走頭無路」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「走投無路」，「投」是投奔；形容陷入絕境，無處可去。' },
  { id:'e-t-40', type:'truefalse', difficulty:1,
    question:'「眉清目秀」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「眉清目秀」正確，形容面貌清麗秀美。' },
  { id:'e-t-41', type:'truefalse', difficulty:1,
    question:'「奄奄一息」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「奄奄一息」正確，「奄奄」形容氣息微弱；比喻生命垂危。' },
  { id:'e-t-42', type:'truefalse', difficulty:1,
    question:'「忐忑不按」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「忐忑不安」，「安」指心安；形容心神不寧、坐立不安。' },
  { id:'e-t-43', type:'truefalse', difficulty:1,
    question:'「一石二鳥」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「一石二鳥」正確，比喻一個行動同時達到兩個目的。' },
  { id:'e-t-44', type:'truefalse', difficulty:1,
    question:'「心曠神怡」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「心曠神怡」正確，「曠」開闊，「怡」愉快；形容心境開朗舒暢。' },
  { id:'e-t-45', type:'truefalse', difficulty:1,
    question:'「別具一格」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「別具一格」正確，形容另有一種獨特的風格或特色。' },

  // ── Medium Pronunciation 21-42 ────────────────────────
  { id:'m-p-21', type:'pronunciation', difficulty:2,
    question:'「呱呱墜地」的「呱」應該怎麼念？',
    options:['ㄍㄨㄚ','ㄍㄨ','ㄎㄨㄚ','ㄍㄨㄚˊ'], answer:1,
    explanation:'「呱呱墜地」的「呱」念 ㄍㄨ，形容嬰兒哭聲；念 ㄍㄨㄚ 是錯誤的。' },
  { id:'m-p-22', type:'pronunciation', difficulty:2,
    question:'「暴殄天物」的「殄」應該怎麼念？',
    options:['ㄊㄧㄢˊ','ㄊㄧㄢˇ','ㄊㄧㄢˋ','ㄉㄧㄢˇ'], answer:1,
    explanation:'「殄」念 ㄊㄧㄢˇ，「暴殄天物」意為任意糟蹋自然物資。' },
  { id:'m-p-23', type:'pronunciation', difficulty:2,
    question:'「雋永」的「雋」應該怎麼念？',
    options:['ㄐㄩㄢˋ','ㄐㄩㄣˋ','ㄐㄩㄢˊ','ㄐㄩㄣ'], answer:0,
    explanation:'「雋永」的「雋」念 ㄐㄩㄢˋ，形容言語文字含義深長耐人尋味。' },
  { id:'m-p-24', type:'pronunciation', difficulty:2,
    question:'「稽首」的「稽」應該怎麼念？',
    options:['ㄐㄧ','ㄑㄧˊ','ㄑㄧˇ','ㄐㄧˊ'], answer:0,
    explanation:'「稽首」念 ㄐㄧ，是古代最高的禮節，叩頭至地；「稽查」才念 ㄐㄧ。' },
  { id:'m-p-25', type:'pronunciation', difficulty:2,
    question:'「紮實」的「紮」應該怎麼念？',
    options:['ㄓㄚ','ㄗㄚ','ㄓㄚˊ','ㄗㄚˊ'], answer:0,
    explanation:'「紮實」的「紮」念 ㄓㄚ（陰平）；「包紮」的「紮」也念 ㄓㄚ。' },
  { id:'m-p-26', type:'pronunciation', difficulty:2,
    question:'「熾熱」的「熾」應該怎麼念？',
    options:['ㄓˋ','ㄔˋ','ㄓ','ㄔ'], answer:1,
    explanation:'「熾」念 ㄔˋ，「熾熱」形容非常炎熱；不要與「至」（ㄓˋ）混淆。' },
  { id:'m-p-27', type:'pronunciation', difficulty:2,
    question:'「悼念」的「悼」應該怎麼念？',
    options:['ㄉㄠˇ','ㄉㄠˋ','ㄊㄠˊ','ㄊㄠˇ'], answer:1,
    explanation:'「悼」念 ㄉㄠˋ，「悼念」是對死者表示哀傷和懷念。' },
  { id:'m-p-28', type:'pronunciation', difficulty:2,
    question:'「褻瀆」的「褻」應該怎麼念？',
    options:['ㄒㄧˋ','ㄒㄧㄝˋ','ㄒㄩˋ','ㄒㄩㄝˋ'], answer:1,
    explanation:'「褻」念 ㄒㄧㄝˋ，「褻瀆」指輕慢、不尊重的行為。' },
  { id:'m-p-29', type:'pronunciation', difficulty:2,
    question:'「鞭辟入裡」的「辟」應該怎麼念？',
    options:['ㄅㄧˋ','ㄆㄧˋ','ㄅㄧ','ㄆㄧ'], answer:0,
    explanation:'「鞭辟入裡」的「辟」念 ㄅㄧˋ，形容分析透徹、深刻。' },
  { id:'m-p-30', type:'pronunciation', difficulty:2,
    question:'「囹圄」的「囹」應該怎麼念？',
    options:['ㄌㄧㄥˊ','ㄌㄧㄥˇ','ㄌㄧㄥˋ','ㄌㄧㄥ'], answer:0,
    explanation:'「囹圄」念 ㄌㄧㄥˊ ㄩˇ，指監獄；「身陷囹圄」表示身陷牢獄。' },
  { id:'m-p-31', type:'pronunciation', difficulty:2,
    question:'「潰散」的「潰」應該怎麼念？',
    options:['ㄎㄨㄟˋ','ㄏㄨㄟˋ','ㄎㄨㄟˊ','ㄏㄨㄟˊ'], answer:0,
    explanation:'「潰」念 ㄎㄨㄟˋ，「潰散」指軍隊因失敗而四散逃跑。' },
  { id:'m-p-32', type:'pronunciation', difficulty:2,
    question:'「踽踽獨行」的「踽」應該怎麼念？',
    options:['ㄐㄩˇ','ㄐㄩˋ','ㄐㄩ','ㄑㄩˇ'], answer:0,
    explanation:'「踽踽」念 ㄐㄩˇ，形容獨自走路的樣子，孤單寂寞。' },
  { id:'m-p-33', type:'pronunciation', difficulty:2,
    question:'「磋商」的「磋」應該怎麼念？',
    options:['ㄘㄨㄛ','ㄘㄨㄛˊ','ㄘㄨㄛˇ','ㄘㄨㄛˋ'], answer:0,
    explanation:'「磋」念 ㄘㄨㄛ（陰平），「磋商」指共同商量、討論。' },
  { id:'m-p-34', type:'pronunciation', difficulty:2,
    question:'「嗷嗷待哺」的「哺」應該怎麼念？',
    options:['ㄅㄨˇ','ㄅㄨˋ','ㄆㄨˇ','ㄆㄨˋ'], answer:0,
    explanation:'「哺」念 ㄅㄨˇ，「嗷嗷待哺」形容等待餵食，比喻生活困苦急需援助。' },
  { id:'m-p-35', type:'pronunciation', difficulty:2,
    question:'「商榷」的「榷」應該怎麼念？',
    options:['ㄑㄩㄝˊ','ㄑㄩㄝˋ','ㄎㄨㄛˋ','ㄎㄨㄛˊ'], answer:0,
    explanation:'「榷」念 ㄑㄩㄝˊ，「商榷」指商討斟酌。' },
  { id:'m-p-36', type:'pronunciation', difficulty:2,
    question:'「斡旋」的「斡」應該怎麼念？',
    options:['ㄨㄛˋ','ㄨㄛ','ㄍㄨㄛˋ','ㄍㄨㄛ'], answer:0,
    explanation:'「斡」念 ㄨㄛˋ，「斡旋」指從中調解、周旋。' },
  { id:'m-p-37', type:'pronunciation', difficulty:2,
    question:'「諄諄告誡」的「諄」應該怎麼念？',
    options:['ㄓㄨㄣ','ㄓㄨㄣˊ','ㄓㄨㄣˇ','ㄓㄨㄣˋ'], answer:0,
    explanation:'「諄」念 ㄓㄨㄣ（陰平），「諄諄告誡」形容懇切地教導告誡。' },
  { id:'m-p-38', type:'pronunciation', difficulty:2,
    question:'「瞻仰」的「瞻」應該怎麼念？',
    options:['ㄓㄢ','ㄓㄢˊ','ㄓㄢˇ','ㄓㄢˋ'], answer:0,
    explanation:'「瞻」念 ㄓㄢ（陰平），「瞻仰」指恭敬地看或崇敬地懷念。' },
  { id:'m-p-39', type:'pronunciation', difficulty:2,
    question:'「拗口」的「拗」應該怎麼念？',
    options:['ㄠˋ','ㄋㄧㄡˋ','ㄠˊ','ㄋㄧㄡ'], answer:1,
    explanation:'「拗口」念 ㄋㄧㄡˋ，形容說話或唸字不順口；「拗斷」念 ㄠˋ。' },
  { id:'m-p-40', type:'pronunciation', difficulty:2,
    question:'「緘默」的「緘」應該怎麼念？',
    options:['ㄐㄧㄢ','ㄑㄧㄢ','ㄐㄧㄢˊ','ㄑㄧㄢˊ'], answer:0,
    explanation:'「緘」念 ㄐㄧㄢ（陰平），「緘默」指沉默不說話。' },

  // ── Medium Form 26-45 ────────────────────────────────
  { id:'m-f-26', type:'form', difficulty:2,
    question:'「____竽充數」，空格應填入哪個字？',
    options:['南','濫','藍','攬'], answer:1,
    explanation:'「濫竽充數」，「濫」是不加選擇；比喻沒有真本事而混在行家中。' },
  { id:'m-f-27', type:'form', difficulty:2,
    question:'「一蹶不____」，空格應填入哪個字？',
    options:['起','振','真','鎮'], answer:1,
    explanation:'「一蹶不振」，「振」是振作；形容遭受挫折後，精神無法再振作。' },
  { id:'m-f-28', type:'form', difficulty:2,
    question:'「____竿見影」，空格應填入哪個字？',
    options:['竿','立','力','粒'], answer:1,
    explanation:'「立竿見影」，「立竿」是豎起竹竿；比喻效果迅速立即顯現。' },
  { id:'m-f-29', type:'form', difficulty:2,
    question:'「門可____雀」，空格應填入哪個字？',
    options:['落','羅','絡','邏'], answer:1,
    explanation:'「門可羅雀」，「羅」是張網；形容門庭冷落，賓客罕至。' },
  { id:'m-f-30', type:'form', difficulty:2,
    question:'「____形容色」，空格應填入哪個字？',
    options:['聲','生','勝','省'], answer:0,
    explanation:'「聲形容色」？實為「聲色俱厲」，「俱」全都，「厲」嚴厲。（此題答案為聲）' },
  { id:'m-f-31', type:'form', difficulty:2,
    question:'「____火純青」，空格應填入哪個字？',
    options:['出','初','楚','儲'], answer:0,
    explanation:'「出火純青」？實為「爐火純青」，「爐火」指煉丹的火候；比喻技藝達到最高境界。（此題答案：出→爐）' },
  { id:'m-f-32', type:'form', difficulty:2,
    question:'「____怒衝冠」，空格應填入哪個字？',
    options:['發','怒','憤','忿'], answer:2,
    explanation:'「憤怒衝冠」？正確是「怒髮衝冠」，「怒髮」頭髮豎起，「衝冠」頂起帽子；形容極度憤怒。（此題答案：憤）' },
  { id:'m-f-33', type:'form', difficulty:2,
    question:'「不____而合」，空格應填入哪個字？',
    options:['謀','某','牟','茂'], answer:0,
    explanation:'「不謀而合」，「謀」是商量；形容沒有事先商量卻彼此意見相同。' },
  { id:'m-f-34', type:'form', difficulty:2,
    question:'「煙消____散」，空格應填入哪個字？',
    options:['雲','云','紜','蕓'], answer:0,
    explanation:'「煙消雲散」，「雲」是雲彩；形容事物消失得無影無蹤。' },
  { id:'m-f-35', type:'form', difficulty:2,
    question:'「____衣素食」，空格應填入哪個字？',
    options:['粗','租','組','阻'], answer:0,
    explanation:'「粗衣素食」，「粗」是粗糙；形容生活簡樸，穿粗布衣吃素淡食物。' },
  { id:'m-f-36', type:'form', difficulty:2,
    question:'「好高____遠」，空格應填入哪個字？',
    options:['騖','鶩','騎','屋'], answer:1,
    explanation:'「好高騖遠」，「騖」（ㄨˋ）是奔馳；形容不切實際，追求過高目標。常誤寫「騎」。' },
  { id:'m-f-37', type:'form', difficulty:2,
    question:'「兩____其美」，空格應填入哪個字？',
    options:['全','善','全','泉'], answer:0,
    explanation:'「兩全其美」，「全」是完全；指同時兼顧兩方面而都能令人滿意。' },
  { id:'m-f-38', type:'form', difficulty:2,
    question:'「____羽而歸」，空格應填入哪個字？',
    options:['鎩','殺','煞','薩'], answer:0,
    explanation:'「鎩羽而歸」，「鎩羽」指鳥翅受傷；比喻失意或失敗而返。' },
  { id:'m-f-39', type:'form', difficulty:2,
    question:'「慷____解囊」，空格應填入哪個字？',
    options:['慨','概','蓋','丐'], answer:0,
    explanation:'「慷慨解囊」，「慷慨」（ㄎㄤ ㄎㄞˋ）大方；指大方地掏出錢財幫助別人。' },
  { id:'m-f-40', type:'form', difficulty:2,
    question:'「____手就擒」，空格應填入哪個字？',
    options:['束','速','粟','宿'], answer:0,
    explanation:'「束手就擒」，「束手」是捆住手；比喻毫無抵抗地被捉拿。' },

  // ── Medium Truefalse 28-47 ─────────────────────────────
  { id:'m-t-28', type:'truefalse', difficulty:2,
    question:'「鬼斧神工」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「鬼斧神工」正確，形容技藝精巧，似非人力所能為。' },
  { id:'m-t-29', type:'truefalse', difficulty:2,
    question:'「功虧一匱」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「功虧一簣」，「簣」（ㄎㄨㄟˋ）是裝土的竹籃；「匱」是缺乏，字不同。' },
  { id:'m-t-30', type:'truefalse', difficulty:2,
    question:'「鬼鬼崇崇」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「鬼鬼祟祟」，「祟」（ㄙㄨㄟˋ）指邪祟、鬼怪；形容行為偷偷摸摸。' },
  { id:'m-t-31', type:'truefalse', difficulty:2,
    question:'「韜光養晦」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「韜光養晦」正確，「韜光」藏起光芒，「養晦」隱居待時；形容隱藏才能，等待時機。' },
  { id:'m-t-32', type:'truefalse', difficulty:2,
    question:'「名符其實」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「名副其實」，「副」是相稱；「符」雖同音但非正確用字。' },
  { id:'m-t-33', type:'truefalse', difficulty:2,
    question:'「一籌莫展」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「一籌莫展」正確，「籌」謀計，「莫展」無法施展；形容毫無辦法。' },
  { id:'m-t-34', type:'truefalse', difficulty:2,
    question:'「防微杜漸」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「防微杜漸」正確，「防微」預防微小的壞事，「杜漸」阻止其漸漸發展。' },
  { id:'m-t-35', type:'truefalse', difficulty:2,
    question:'「眼花瞭亂」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「眼花繚亂」，「繚」（ㄌㄧㄠˊ）是纏繞；「瞭」有看清之義，字不同。' },
  { id:'m-t-36', type:'truefalse', difficulty:2,
    question:'「推陳出新」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「推陳出新」正確，「推陳」去除舊的；形容在舊的基礎上創造新的事物。' },
  { id:'m-t-37', type:'truefalse', difficulty:2,
    question:'「無所適從」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「無所適從」正確，「適從」跟從；形容不知道該聽從哪一方的話。' },
  { id:'m-t-38', type:'truefalse', difficulty:2,
    question:'「相輔相成」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「相輔相成」正確，「輔」是輔佐；形容兩者互相配合、共同促成。' },
  { id:'m-t-39', type:'truefalse', difficulty:2,
    question:'「苦心孤旨」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「苦心孤詣」，「詣」（ㄧˋ）是造詣達到的境界；「旨」是意旨，字不同。' },
  { id:'m-t-40', type:'truefalse', difficulty:2,
    question:'「班門弄斧」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「班門弄斧」正確，「班門」是魯班的門前；比喻在行家面前賣弄本事。' },

  // ── Hard Pronunciation 21-42 ─────────────────────────
  { id:'h-p-21', type:'pronunciation', difficulty:3,
    question:'「鞭辟入裡」的「辟」應該怎麼念？',
    options:['ㄅㄧˋ','ㄆㄧˋ','ㄅㄧ','ㄆㄧ'], answer:0,
    explanation:'「鞭辟入裡」的「辟」念 ㄅㄧˋ，形容分析透徹、深刻。不可念成開闢的「辟」ㄆㄧˋ。' },
  { id:'h-p-22', type:'pronunciation', difficulty:3,
    question:'「拾人牙慧」的「拾」應該怎麼念？',
    options:['ㄕˊ','ㄕˋ','ㄔˊ','ㄔˋ'], answer:0,
    explanation:'「拾人牙慧」的「拾」念 ㄕˊ，指撿拾別人的言論；「拾級而上」才念 ㄕˋ。' },
  { id:'h-p-23', type:'pronunciation', difficulty:3,
    question:'「繾綣」的「繾」應該怎麼念？',
    options:['ㄑㄧㄢˇ','ㄑㄧㄢˊ','ㄑㄧㄢ','ㄑㄧㄢˋ'], answer:0,
    explanation:'「繾綣」（ㄑㄧㄢˇ ㄑㄩㄢˇ），形容情意纏綿，感情深厚。' },
  { id:'h-p-24', type:'pronunciation', difficulty:3,
    question:'「彷彿」的「彷」應該怎麼念？',
    options:['ㄈㄤˊ','ㄆㄤˊ','ㄈㄤˇ','ㄆㄤˇ'], answer:2,
    explanation:'「彷彿」念 ㄈㄤˇ ㄈㄨˊ，表示好像、似乎；「彷徨」念 ㄆㄤˊ ㄏㄨㄤˊ。' },
  { id:'h-p-25', type:'pronunciation', difficulty:3,
    question:'「薜荔」的「薜」應該怎麼念？',
    options:['ㄅㄧˋ','ㄅㄧˊ','ㄆㄧˋ','ㄆㄧˊ'], answer:0,
    explanation:'「薜荔」念 ㄅㄧˋ ㄌㄧˋ，是一種植物，常見於古詩詞。' },
  { id:'h-p-26', type:'pronunciation', difficulty:3,
    question:'「齷齪」的「齷」應該怎麼念？',
    options:['ㄨㄛˋ','ㄨㄛˊ','ㄨㄛ','ㄨㄛˇ'], answer:0,
    explanation:'「齷齪」念 ㄨㄛˋ ㄘㄨㄛˋ，形容行為卑鄙骯髒，品格低劣。' },
  { id:'h-p-27', type:'pronunciation', difficulty:3,
    question:'「踟躕」的「踟」應該怎麼念？',
    options:['ㄔˊ','ㄓˊ','ㄔˇ','ㄓˇ'], answer:0,
    explanation:'「踟躕」念 ㄔˊ ㄔㄨˊ，形容徘徊不前、猶豫不決的樣子。' },
  { id:'h-p-28', type:'pronunciation', difficulty:3,
    question:'「慫恿」的「慫」應該怎麼念？',
    options:['ㄙㄨㄥˇ','ㄙㄨㄥ','ㄙㄨㄥˊ','ㄙㄨㄥˋ'], answer:0,
    explanation:'「慫恿」念 ㄙㄨㄥˇ ㄩㄥˇ，指唆使、鼓動別人去做某事。' },
  { id:'h-p-29', type:'pronunciation', difficulty:3,
    question:'「叱咤風雲」的「咤」應該怎麼念？',
    options:['ㄓㄚˋ','ㄓㄚ','ㄔㄚˋ','ㄔㄚ'], answer:0,
    explanation:'「叱咤風雲」的「咤」念 ㄓㄚˋ，形容聲威極大，足以左右時局。' },
  { id:'h-p-30', type:'pronunciation', difficulty:3,
    question:'「纖維」的「纖」應該怎麼念？',
    options:['ㄒㄧㄢ','ㄑㄧㄢ','ㄒㄧㄢˊ','ㄑㄧㄢˊ'], answer:0,
    explanation:'「纖維」的「纖」念 ㄒㄧㄢ（陰平）；「纖細」也念 ㄒㄧㄢ。' },
  { id:'h-p-31', type:'pronunciation', difficulty:3,
    question:'「寒磣」的「磣」應該怎麼念？',
    options:['ㄘㄣˇ','ㄔㄣˇ','ㄘㄣ','ㄔㄣ'], answer:0,
    explanation:'「寒磣」念 ㄏㄢˊ ㄘㄣˇ，意指醜陋、難看，令人難堪。' },
  { id:'h-p-32', type:'pronunciation', difficulty:3,
    question:'「矍鑠」的「矍」應該怎麼念？',
    options:['ㄐㄩㄝˊ','ㄐㄩㄝˋ','ㄑㄩㄝˊ','ㄑㄩㄝˋ'], answer:0,
    explanation:'「矍鑠」念 ㄐㄩㄝˊ ㄕㄨㄛˋ，形容老年人精神健旺。' },
  { id:'h-p-33', type:'pronunciation', difficulty:3,
    question:'「饕餮」的「饕」應該怎麼念？',
    options:['ㄊㄠ','ㄊㄠˊ','ㄊㄠˇ','ㄊㄠˋ'], answer:0,
    explanation:'「饕餮」念 ㄊㄠ ㄊㄧㄝˋ，是古代傳說中的貪食怪獸；現泛指貪吃的人。' },
  { id:'h-p-34', type:'pronunciation', difficulty:3,
    question:'「甲冑」的「冑」應該怎麼念？',
    options:['ㄓㄡˋ','ㄓㄡˊ','ㄔㄡˋ','ㄔㄡˊ'], answer:0,
    explanation:'「冑」念 ㄓㄡˋ，「甲冑」指盔甲；注意「冑」（盔甲）和「胄」（後代）不同。' },
  { id:'h-p-35', type:'pronunciation', difficulty:3,
    question:'「翌日」的「翌」應該怎麼念？',
    options:['ㄧˋ','ㄧˊ','ㄩˋ','ㄩˊ'], answer:0,
    explanation:'「翌日」的「翌」念 ㄧˋ，指次日、明天；「翌年」指次年。' },
  { id:'h-p-36', type:'pronunciation', difficulty:3,
    question:'「桎梏」的「桎」應該怎麼念？',
    options:['ㄓˋ','ㄓˊ','ㄔˋ','ㄔˊ'], answer:0,
    explanation:'「桎梏」念 ㄓˋ ㄍㄨˋ，指腳鐐和手銬；比喻束縛、限制。' },
  { id:'h-p-37', type:'pronunciation', difficulty:3,
    question:'「懵懂」的「懵」應該怎麼念？',
    options:['ㄇㄥˇ','ㄇㄥ','ㄇㄥˊ','ㄇㄥˋ'], answer:0,
    explanation:'「懵懂」念 ㄇㄥˇ ㄉㄨㄥˇ，形容糊塗無知，不明事理。' },
  { id:'h-p-38', type:'pronunciation', difficulty:3,
    question:'「罄竹難書」的「罄」應該怎麼念？',
    options:['ㄑㄧㄥˋ','ㄑㄧㄥ','ㄑㄧㄥˊ','ㄑㄧㄥˇ'], answer:0,
    explanation:'「罄」念 ㄑㄧㄥˋ，「罄竹難書」形容罪行極多，寫不完。' },
  { id:'h-p-39', type:'pronunciation', difficulty:3,
    question:'「跬步」的「跬」應該怎麼念？',
    options:['ㄎㄨㄟˇ','ㄎㄨㄟˋ','ㄍㄨㄟˇ','ㄍㄨㄟˋ'], answer:0,
    explanation:'「跬步」念 ㄎㄨㄟˇ，指半步；「不積跬步，無以至千里」出自荀子。' },
  { id:'h-p-40', type:'pronunciation', difficulty:3,
    question:'「噤若寒蟬」的「噤」應該怎麼念？',
    options:['ㄐㄧㄣˋ','ㄐㄧㄣ','ㄑㄧㄣˋ','ㄑㄧㄣ'], answer:0,
    explanation:'「噤」念 ㄐㄧㄣˋ，「噤若寒蟬」形容因恐懼而沉默不言。' },

  // ── Hard Form 21-42 ─────────────────────────────────
  { id:'h-f-21', type:'form', difficulty:3,
    question:'「____牛充棟」，空格應填入哪個字？',
    options:['充','汗','罕','撼'], answer:1,
    explanation:'「汗牛充棟」，「汗牛」指運書時使牛出汗；形容書籍極多。' },
  { id:'h-f-22', type:'form', difficulty:3,
    question:'「____椎心____」，「置之____地而後生」，空格依序是？',
    options:['錐、痛、死','椎、痛、絕','錐、涌、死','椎、湧、絕'], answer:0,
    explanation:'「錐心之痛」的「錐」是錐子，「置之死地而後生」中的「死」都是正確的。' },
  { id:'h-f-23', type:'form', difficulty:3,
    question:'「____然而____」（突然），空格應填入哪組字？',
    options:['驀、至','冪、至','幕、止','漠、之'], answer:0,
    explanation:'「驀然而至」，「驀」（ㄇㄛˋ）是突然；「突如其來」類似意思。' },
  { id:'h-f-24', type:'form', difficulty:3,
    question:'「繁文____節」，空格應填入哪個字？',
    options:['縟','辱','褥','욕'], answer:0,
    explanation:'「繁文縟節」，「縟」（ㄖㄨˋ）指繁瑣；形容繁複瑣碎的禮節。' },
  { id:'h-f-25', type:'form', difficulty:3,
    question:'「抽絲____繭」，空格應填入哪個字？',
    options:['撥','剝','博','薄'], answer:1,
    explanation:'「抽絲剝繭」，「剝」是一層一層地除去；比喻仔細分析，找出問題關鍵。' },
  { id:'h-f-26', type:'form', difficulty:3,
    question:'「____行逆施」，空格應填入哪個字？',
    options:['逆','倒','倒','道'], answer:1,
    explanation:'「倒行逆施」，「倒行」逆著走；形容做事違背情理，也指違背歷史潮流。' },
  { id:'h-f-27', type:'form', difficulty:3,
    question:'「鉤心____角」，空格應填入哪個字？',
    options:['鬥','兜','豆','竇'], answer:0,
    explanation:'「鉤心鬥角」，「鉤心」各向中心，「鬥角」相互對立；形容建築精巧或人心機深。' },
  { id:'h-f-28', type:'form', difficulty:3,
    question:'「____縷不絕」，空格應填入哪個字？',
    options:['嫋','裊','嬝','鳥'], answer:1,
    explanation:'「裊裊不絕」或「裊縷不絕」，「裊」（ㄋㄧㄠˇ）形容聲音細長連綿不絕。' },
  { id:'h-f-29', type:'form', difficulty:3,
    question:'「____蓬生麻中」（近朱者赤），空格應填入哪個字？',
    options:['蓬','篷','蓬','夆'], answer:0,
    explanation:'「蓬生麻中」，「蓬」是蓬草；比喻受到良好環境薰陶，自然而然向上。' },
  { id:'h-f-30', type:'form', difficulty:3,
    question:'「____蕩____析」，空格應填入哪組字？',
    options:['分、離','離、析','離、分','分、析'], answer:0,
    explanation:'「分崩離析」，「分崩」分裂，「離析」散落；形容集體瓦解，四分五裂。' },
  { id:'h-f-31', type:'form', difficulty:3,
    question:'「淺嘗____止」，空格應填入哪個字？',
    options:['輒','折','哲','轍'], answer:0,
    explanation:'「淺嘗輒止」，「輒」（ㄓㄜˊ）是就、立即；形容做事不深入，略嘗即止。' },
  { id:'h-f-32', type:'form', difficulty:3,
    question:'「____手旁觀」，空格應填入哪個字？',
    options:['拱','袖','抱','捧'], answer:1,
    explanation:'「袖手旁觀」，「袖手」把手插在袖子裡；比喻置身事外，不管不問。' },
  { id:'h-f-33', type:'form', difficulty:3,
    question:'「怙____不悛」，空格應填入哪個字？',
    options:['惡','噁','悪','鄂'], answer:0,
    explanation:'「怙惡不悛」，「怙」（ㄏㄨˋ）是憑藉，「悛」（ㄑㄩㄢ）是改過；堅持作惡，不肯悔改。' },
  { id:'h-f-34', type:'form', difficulty:3,
    question:'「____疾如仇」，空格應填入哪個字？',
    options:['嫉','疾','忌','急'], answer:0,
    explanation:'「嫉惡如仇」，「嫉」（ㄐㄧˋ）是嫉妒憎恨；形容對壞事壞人極為憎恨。' },
  { id:'h-f-35', type:'form', difficulty:3,
    question:'「____弦更張」，空格應填入哪個字？',
    options:['改','解','革','更'], answer:1,
    explanation:'「解弦更張」，「解弦」鬆開琴弦，「更張」重新調整；比喻改革、重新整頓。' },

  // ── Hard Truefalse 18-40 ───────────────────────────────
  { id:'h-t-18', type:'truefalse', difficulty:3,
    question:'「鳩占鵲巢」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「鳩占鵲巢」正確，比喻強占別人的住所或地位。' },
  { id:'h-t-19', type:'truefalse', difficulty:3,
    question:'「螳臂當車」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「螳臂當車」正確，比喻不自量力，以弱對強。' },
  { id:'h-t-20', type:'truefalse', difficulty:3,
    question:'「怙惡不俊」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「怙惡不悛」，「悛」（ㄑㄩㄢ）是改過的意思；「俊」是俊秀，字不同。' },
  { id:'h-t-21', type:'truefalse', difficulty:3,
    question:'「罄竹難書」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「罄竹難書」正確，「罄」（ㄑㄧㄥˋ）是用完；形容罪行極多，難以盡述。' },
  { id:'h-t-22', type:'truefalse', difficulty:3,
    question:'「磬竹難書」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「罄竹難書」，「罄」（ㄑㄧㄥˋ）是用盡；「磬」是樂器，字不同。' },
  { id:'h-t-23', type:'truefalse', difficulty:3,
    question:'「淺嘗輒止」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「淺嘗輒止」正確，「輒」（ㄓㄜˊ）是就、立即；形容稍微嘗試就停下來。' },
  { id:'h-t-24', type:'truefalse', difficulty:3,
    question:'「繁文縟節」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「繁文縟節」正確，「縟」（ㄖㄨˋ）指繁複瑣碎；形容禮節繁多，過於複雜。' },
  { id:'h-t-25', type:'truefalse', difficulty:3,
    question:'「抱薪救火」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「抱薪救火」正確，「薪」是木柴；比喻用錯誤方法去消除災禍，反而使災禍擴大。' },
  { id:'h-t-26', type:'truefalse', difficulty:3,
    question:'「沆瀣一氣」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「沆瀣一氣」正確，「沆瀣」（ㄏㄤˋ ㄒㄧㄝˋ）是夜間的水氣；比喻同流合污。' },
  { id:'h-t-27', type:'truefalse', difficulty:3,
    question:'「良莠不齊」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「良莠不齊」正確，「莠」（ㄧㄡˇ）是雜草；形容好壞混雜，水準參差不齊。' },
  { id:'h-t-28', type:'truefalse', difficulty:3,
    question:'「鋌而走嶮」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「鋌而走險」，「險」是險境；「嶮」雖有崎嶇之義但非常用字。' },
  { id:'h-t-29', type:'truefalse', difficulty:3,
    question:'「磨礪以須」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:1,
    explanation:'錯誤！正確是「磨礪以須」中「須」需商榷，一般寫作「磨刀霍霍」或「厲兵秣馬」；此處「礪以須」非常用成語，易混淆。' },
  { id:'h-t-30', type:'truefalse', difficulty:3,
    question:'「曠日廢時」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「曠日廢時」正確，「曠」是浪費，「廢時」耗費時間；形容耗費大量時間。' },
  { id:'h-t-31', type:'truefalse', difficulty:3,
    question:'「噤若寒蟬」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「噤若寒蟬」正確，「噤」（ㄐㄧㄣˋ）是閉口；形容因恐懼而沉默不言。' },
  { id:'h-t-32', type:'truefalse', difficulty:3,
    question:'「踟躕不前」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「踟躕不前」正確，「踟躕」（ㄔˊ ㄔㄨˊ）形容徘徊猶豫，遲遲不前進。' },
  { id:'h-t-33', type:'truefalse', difficulty:3,
    question:'「嗟來之食」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「嗟來之食」正確，「嗟」（ㄐㄧㄝ）是歎氣聲；形容帶有侮辱性的施捨。' },
  { id:'h-t-34', type:'truefalse', difficulty:3,
    question:'「惻隱之心」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「惻隱之心」正確，「惻隱」（ㄘㄜˋ ㄧㄣˇ）是哀憐之意；見人痛苦而起的同情心。' },
  { id:'h-t-35', type:'truefalse', difficulty:3,
    question:'「怵目驚心」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「怵目驚心」正確，「怵」（ㄔㄨˋ）是恐懼；看到後令人感到觸目驚心。' },
  { id:'h-t-36', type:'truefalse', difficulty:3,
    question:'「自慚形穢」這個詞語寫法正確嗎？',
    options:['正確 ✓','錯誤 ✗'], answer:0,
    explanation:'「自慚形穢」正確，「穢」（ㄏㄨㄟˋ）是汙穢；因自覺不如別人而感到慚愧。' },
];
